---
monit_version: 1:5.16-2
monit_slack_user: Monit - Alerter
monitor_alerts_slack_url: ""
monitor_alerts_slack_channel: ""
monit_slack_webhook_url: "{{ monitor_alerts_slack_url }}"
monit_slack_channel: "{{ monitor_alerts_slack_channel }}"

# Override values based on templates starting with check_
monit_checks: []

# Override these values in group vars
alertmanager_host: localhost
alertmanager_port: 9093
prometheus_host: localhost
prometheus_port: 9090

