- name: install psycopg2
  package:
    name: python-psycopg2
    state: present

- name: Verifying db users are present else creating them
  include: databases.yml

- name: creating database
  include: users.yml

- name: Copy the templates
  become: yes
  template: src={{item}} dest=/tmp/{{item}}
  with_items:
    - programs_postgres.sql
    - enc_postgres.sql

- name: Install postgres client to create schema from file
  apt:
    name: postgresql-client
    state: present
    update_cache: yes

- name: Create the schema for programs service
  postgresql_db:
    login_user: "{{ programs_service_postgres_username }}"
    login_password: "{{ programs_service_postgres_password }}"
    login_host: "{{ programs_service_postgres_host }}"
    name: "{{ programs_postgres_db }}"
    state: restore
    target: "/tmp/programs_postgres.sql"

- name: Create tables for enc service
  postgresql_db:
    login_user: "{{ enc_postgres_user }}"
    login_password: "{{ enc_postgres_password }}"
    login_host: "{{ enc_postgres_host }}"
    name: "{{ enc_postgres_database }}"
    state: restore
    target: "/tmp/enc_postgres.sql"
