apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kibana-oauth-vs
  namespace: {{ .Values.namespace }}
spec:
  gateways:
  - public-gateway
  hosts:
  - {{ .Values.domain_name }} 
  http:
  - match:
    - uri:
        prefix: /dashboard/
    - uri:
        prefix: /dashboard
    route:
    - destination:
        host: oauth2-proxy.logging.svc.cluster.local
  - match:
    - uri:
        prefix: /oauth2
    route:
    - destination:
        host: oauth2-proxy.logging.svc.cluster.local
