apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: encryption-vs
  namespace: {{ .Values.namespace }}
spec:
  gateways:
  - public-gateway
  hosts:
  - {{ .Values.domain_name }} 
  http:
  - match:
    - uri:
        prefix: /thirdparty
    route:
    - destination:
        host: player
      headers:
        request:
          add:
            Cache-Control: public
            Pragma: public
  - match:
    - uri:
        prefix: /oauth2callback
    route:
    - destination:
        host: player
    fault:
      abort:
        httpStatus: 200    
  - route:
    - destination:
        host: player
