apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ .Values.namespace }}-kibana
  namespace: {{ .Values.namespace }}
spec:
  endpoints:
  - address: {{ .Values.swarm_manager_ip }}
  hosts:
  - kibana.{{ .Values.namespace }}.global
  location: MESH_INTERNAL
  ports:
  - name: kibana
    number: 5601
    protocol: HTTP
  resolution: STATIC
