learner_user: learning
learner_user_home: /home/{{learner_user}}
logstash_version: 6.3.1
logstash_home: "{{learner_user_home}}/logstash-{{logstash_version}}"

lms_kafka_url: "{{groups['processing-cluster-kafka']|join(':9092,')}}:9092"
lms_kafka_topic_id: "{{env}}.lms.audit.events"
lms_audit_log_file_name: lms_audit_events
lms_audit_log_file_path: /data/logs/{{lms_audit_log_file_name}}.log
platform:
 logstash_config: ['logstash-lms']
