---
- name: add rpm key for elastic.co
  rpm_key:
    key: "{{ filebeat_gpg_url }}"

- name: create beats yum repo
  yumrepo:
    name: beats
    baseurl: "{{ filebeat_repo_url }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ filebeat_gpg_url }}"

- name: install filebeat
  yum:
    name: "filebeat-{{ filebeat_version }}"
    state: present
  notify:
    - restart filebeat
