version: '3.3'
services:
  registry:
    image: sunbird/registry_image:2.0-bronze
    ports:
      - "5001:5000"
    deploy:
      replicas: {{ registry_replicas | default(1) }}
      resources:
       reservations:
         memory: "{{ registry_reservation_memory | default('256M') }}"
       limits:
         memory: "{{ registry_limit_memory | default('512M') }}"
    environment:
      TCP_PORTS: '5000'
      VIRTUAL_HOST: '*:5000, https://*:5000'
      FORCE_SSL: 'true'
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
      REGISTRY_AUTH: 'htpasswd'
      REGISTRY_AUTH_HTPASSWD_REALM: 'custom_random_generated_text_for_realm'
      REGISTRY_AUTH_HTPASSWD_PATH: 'htpasswd'
      REGISTRY_STORAGE: azure
      REGISTRY_STORAGE_AZURE_ACCOUNTNAME: "{{registry_storage_azure_accountname}}"
      REGISTRY_STORAGE_AZURE_ACCOUNTKEY: "{{registry_storage_azure_accountkey}}"
      REGISTRY_STORAGE_AZURE_CONTAINER: "{{registry_storage_azure_container}}"
      REGISTRY_INITIAL_USER: "{{registry_initial_user}}"
      REGISTRY_INITIAL_PASSWORD: "{{registry_initial_password}}"
    networks:
      - registry_default    

  registryui:
    image: konradkleine/docker-registry-frontend:v2
    environment:
      VIRTUAL_HOST: '*, https://*'
      ENV_DOCKER_REGISTRY_HOST: 'registry_registry'
      ENV_DOCKER_REGISTRY_PORT: 5001
    ports:
      - "81:80"
    networks:
      - registry_default
     
networks:
  registry_default:
    external: true
