- name: Copy the jar
  become: yes
  copy:
    src: "{{cassandra_jar_path}}/externalId-migration-util-1.0-SNAPSHOT-jar-with-dependencies.jar"
    dest: "{{cassandra_deploy_path}}"
  run_once: true

- name: Run the application
  shell: java -jar externalId-migration-util-1.0-SNAPSHOT-jar-with-dependencies.jar
  run_once: true
