---

- name: enable debian backports
  apt_repository:
    repo: "deb http://cdn.debian.net/debian {{ ansible_distribution_release }}-backports main contrib non-free"
    state: present
  when: ansible_distribution_release == "jessie"

- name: install prometheus-node-exporter
  apt:
    name: prometheus-node-exporter
    default_release: "{{ ansible_distribution_release }}-backports"
    state: present
  when: ansible_distribution_release == "jessie"

- name: install prometheus-node-exporter
  apt:
    name: prometheus-node-exporter
    state: present
  when: ansible_distribution == "Debian" and ansible_distribution_version|int >= 8

- name: /etc/default/prometheus-node-exporter
  template:
    dest: /etc/default/prometheus-node-exporter
    src: prometheus-node-exporter.j2
    owner: root
    group: root
    mode: 0644
  notify: restart prometheus-node-exporter

- name: start and enable the prometheus-node-exporter service
  service:
    name: prometheus-node-exporter
    state: started
    enabled: yes

# - name: copy file_sd_config to prometheus hosts
#   template:
#     dest: "{{ item.path }}"
#     src: file_sd_config.yml.j2
#     owner: root
#     group: root
#     mode: 0644
#   delegate_to: "{{ item.host }}"
#   with_items: "{{ prometheus_node_exporter_file_sd_locations }}"
#   when: prometheus_node_exporter_file_sd
