version: '3.3'

services:
  proxy:
    image: "{{hub_org}}/{{image_name}}:{{image_tag}}"
    ports:
      - "443:443"
      - "80:80"
    deploy:
      replicas: {{ proxy_replicas }}
      resources:
        reservations:
          memory: "{{ proxy_reservation_memory }}"
        limits:
          memory: "{{ proxy_limit_memory }}"
      update_config:
        parallelism: 1
        delay: 30s
    secrets:
{# Skip copying ssls for no domain configs #}
{% if proto=='https' %}
      - site.key
      - site.crt
{% endif %}
      - prom_admin_creds
    configs:
      - source: nginx.conf
        target: /etc/nginx/nginx.conf
      - source: proxy-default.conf
        target: /etc/nginx/conf.d/default.conf
      - source: sunbird-space.conf
        target: /etc/nginx/conf.d/space.conf
    networks:
      - application_default

secrets:
{# Skip copying ssls for no domain configs #}
{% if proto=='https' %}
  site.key:
    external: true
  site.crt:
    external: true
{% endif %}
  prom_admin_creds:
    external: true

configs:
  nginx.conf:
    external: true
  proxy-default.conf:
    external: true
  sunbird-space.conf:
    external: true

networks:
  application_default:
    external: true
