- name: Debian - Add Elasticsearch repository key
  apt_key: url="https://artifacts.elastic.co/GPG-KEY-elasticsearch" state=present

- name: Add curator {{ es_curator_major_version }} repo
  apt_repository: repo='deb [arch=amd64] http://packages.elastic.co/curator/{{ es_curator_major_version }}/debian stable main' state=present update_cache=yes

- debug:
    msg: "{{ es_curator_version }}"

- name: Install elasticsearch curator
  apt:
    name: elasticsearch-curator={{ es_curator_version }}
    force: yes
