- name: Copy the templates
  become: yes
  copy: src=files/{{item}} dest=/tmp/{{item}}
  with_items:
             - pageMgmt.csv
             - pageSection.csv
  tags: 
       - always
  run_once: true

- name: Copy the templates
  become: yes
  template: src={{item}} dest=/tmp/{{item}}
  with_items:
             - cassandra.cql
             - content_service.cql
  tags: 
       - always
  run_once: true
  
- name: Run the cassandra.cql command
  become: yes
  command: "cqlsh -f /tmp/cassandra.cql"
  ignore_errors: yes
  tags: 
       - cql
  run_once: true

- name: Run the pageMgmt.csv command
  become: yes
  command: cqlsh -e "COPY sunbird.page_management(id, appmap,createdby ,createddate ,name ,organisationid ,portalmap ,updatedby ,updateddate ) FROM '/tmp/pageMgmt.csv'" 
  ignore_errors: yes
  tags: 
       - pagemanagement
  run_once: true

- name: Run the pageSection.csv file
  become: yes
  command: cqlsh -e "COPY sunbird.page_section(id, alt,createdby ,createddate ,description ,display ,imgurl ,name,searchquery , sectiondatatype ,status , updatedby ,updateddate) FROM '/tmp/pageSection.csv'"
  ignore_errors: yes
  tags: 
       - pagesection
  run_once: true

- name: Run the content_service.cql file
  become: yes
  command: "cqlsh -f /tmp/content_service.cql"
  ignore_errors: yes
  tags: 
       - content_service
  run_once: true

- name: download 
  become: yes
  command: wget https://github.com/project-sunbird/sunbird-utils/releases/download/release-1.13.0/cassandra-migration-0.0.1-SNAPSHOT-jar-with-dependencies.jar
  args:
    chdir: /tmp
  run_once: true

- name: Run the application
  command: java -cp "cassandra-migration-0.0.1-SNAPSHOT-jar-with-dependencies.jar" com.contrastsecurity.cassandra.migration.utils.MigrationScriptEntryPoint
  args:
      chdir: /tmp
  environment:
    sunbird_cassandra_host: "{{ groups['cassandra'][0] }}"
    sunbird_cassandra_port: 9042
  run_once: true
