es_version: 5.4.3
es_java_install: false
es_api_host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
es_config: {
    node.name: "{{ es_instance_name }}",
    cluster.name: "{{ es_etc_cluster_name }}",
    network.host: "{{ es_api_host }}",
    discovery.zen.ping.unicast.hosts: "{{ groups['es'] }}",
    node.data: "{{ es_etc_node_data }}",
    node.master: "{{ es_etc_node_master }}",
    discovery.zen.minimum_master_nodes: "{{ es_etc_discovery_zen_minimum_master_nodes }}",
    bootstrap.memory_lock: true,
    cloud.azure.storage.my_account: {
      account: "{{ backup_storage_name }}",
      key: "{{ backup_storage_key }}"
    }
}
es_plugins:
  - plugin: repository-azure
es_plugins_reinstall: true
es_snapshot_host: "{{ groups['es-backup'][0] }}"
es_restore_host: "{{ groups['es-backup'][0] }}"
snapshot_base_path: application
