---
# This playbook  deploys the mongodb configurationdb  servers

- name: Create data directory for mongoc configuration server
  file: path={{ mongodb_datadir_prefix }}/configdb state=directory owner=mongod group=mongod

- name: Create the mongodb startup file
  template: src=mongoc.service dest=/etc/systemd/system/mongoc.service mode=0644 seuser=system_u

- name: Create the mongodb configuration file
  template: src=mongoc.conf.j2 dest=/etc/mongoc.conf

- name: Copy the keyfile for authentication
  copy:
    src: roles/mongod/files/secret
    dest: "{{ mongodb_datadir_prefix }}/secret"
    owner: mongod
    group: mongod
    mode: 0400
    setype: mongod_var_lib_t

- name: Start the mongodb service
  systemd: name=mongoc state=started daemon_reload=yes enabled=yes

- wait_for:
    port: "{{ mongoc_port }}"
    delay: 3

- name: Create the file to initialize mongo user
  template: src=mongoc_init.js.j2 dest=/tmp/mongoc_init.js
  when: "{{inventory_hostname == groups['mongoc_servers'][0]}}"

- name: Create admin User
  shell: /usr/bin/mongo "localhost:{{ mongoc_port }}/admin" /tmp/mongoc_init.js
  when: "{{inventory_hostname == groups['mongoc_servers'][0]}}"
  ignore_errors: yes

#- name: add the admin user
#  mongodb_user:
#    login_database: admin
#    login_port: "{{ mongoc_port }}"
#    database: admin
#    name: admin
#    password: "{{ mongo_admin_pass }}"
#    state: present
#  ignore_errors: yes
