- name: install psycopg2
  package:
    name: python-psycopg2
    state: present
- name: ensure backup dir exists
  file: path="{{ postgresql_backup_dir }}" state=directory mode=0777

- set_fact:
    postgresql_backup_gzip_file_name: "postgresql_backup_{{ lookup('pipe', 'date +%Z-%Y-%m-%d-%H-%M-%S') }}"

- set_fact:
    postgresql_backup_gzip_file_path: "{{ postgresql_backup_dir }}/{{ postgresql_backup_gzip_file_name }}.zip"


- name: Dump an existing database to a file
  postgresql_db:
    login_user: "{{ sunbird_pg_user }}"
    login_password: "{{ postgres_password }}"
    login_host: "{{ postgres_hostname }}"
    name: "{{ item }}"
    state: dump
    target: "/tmp/postgres/{{ item }}.sql"
  with_items: "{{ db_name.db }}"

- name: Create archive of backup directory
  archive: path="{{ postgresql_backup_dir }}/" dest="{{ postgresql_backup_dir }}/{{ postgresql_backup_gzip_file_name }}.zip" format=zip

- name: Ensure azure blob storage container exists
  command: az storage container create  --name {{ postgresql_backup_azure_container_name }}
  ignore_errors: true
  environment:
    AZURE_STORAGE_ACCOUNT: "{{ backup_azure_storage_account_name }}"
    AZURE_STORAGE_KEY: "{{ backup_azure_storage_access_key }}"

- name: Upload to azure blob storage
  command: az storage blob upload --name {{ postgresql_backup_gzip_file_name }} --file {{ postgresql_backup_gzip_file_path }} --container-name {{ postgresql_backup_azure_container_name }}
  environment:
    AZURE_STORAGE_ACCOUNT: "{{ backup_azure_storage_account_name }}"
    AZURE_STORAGE_KEY: "{{ backup_azure_storage_access_key }}"
  async: 3600
  poll: 10

- name: clean up backup dir after upload
  file: path="{{ postgresql_backup_dir }}" state=absent
