#apiVersion: v1
#data:
#  {{- range $key, $val := .Values.knowledgemwenv }}
#  {{ $key }}: {{ $val }}
#  {{- end }}
#  sunbird_cassandra_replication_strategy: {{ .Values.sunbird_cassandra_replication_strategy | toJson }}
#kind: ConfigMap
#metadata:
#  creationTimestamp: null
#  name: {{ .Chart.Name }}-config
#  namespace: {{ .Values.namespace }}
