apiVersion: v1
data:
  {{- range $key, $val := .Values.playerenv }}
  {{ $key }}: {{ $val }}
  {{- end }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.namespace }}
