- name: status service
  become: yes
  command: /etc/init.d/keycloak status
  register: keycloak
  poll: 5
  async: 10

- name: stop service
  become: yes
  command: /etc/init.d/keycloak stop && Pkill keycloak
  when: "keycloak.stdout.find('running') != -1"
  poll: 5
  async: 10
  ignore_errors: yes

- name: remove keycloak
  become: yes
  file: path="{{keycloak_home}}" state=absent


- name: change build script permissions
  become: yes
  file: path=/opt owner={{wildfly_user}} group={{wildfly_group}} mode=0755 recurse=yes

- name: get the keycloak tarball
  get_url: url=https://downloads.jboss.org/keycloak/3.2.0.Final/keycloak-3.2.0.Final.tar.gz dest=/opt/keycloak-3.2.0.Final.tar.gz force=no owner={{wildfly_user}} group={{wildfly_group}}

- name: extarct the folder
  unarchive: src=/opt/keycloak-3.2.0.Final.tar.gz dest=/opt/ copy=no owner={{wildfly_user}} group={{wildfly_group}}

- name: move the folder name
  command: mv keycloak-3.2.0.Final keycloak
  args:
       chdir: /opt

- name: remove the keycloak-3.2.0.Final
  become: yes
  file: path=/opt/keycloak-3.2.0.Final state=absent

- name: copy the artifacts
  copy: src={{keycloak_theme_path}} dest="{{keycloak_home}}/themes/" owner={{wildfly_user}} group={{wildfly_group}}

- name: XML file
  template:
    src: standalone-ha.xml
    dest: "{{keycloak_home}}/standalone/configuration/standalone-ha.xml"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    mode: 0750

- name: Create driver directory
  file:
    path: "{{keycloak_home}}/modules/system/layers/keycloak/org/postgresql/main"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    mode: 750
    state: directory
  when: keycloak_ds_driver_url and
        keycloak_ds_driver_name and
        keycloak_ds_driver_module and
        keycloak_custom_driver


- name: Download driver
  get_url:
    url: https://jdbc.postgresql.org/download/postgresql-9.4.1212.jar
    dest: "{{keycloak_home}}/modules/system/layers/keycloak/org/postgresql/main"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    mode: 0750
  when: keycloak_ds_driver_url and
        keycloak_ds_driver_name and
        keycloak_ds_driver_module and
        keycloak_custom_driver


- name: Copy module.xml
  template:
    src: module.xml.j2
    dest: "{{keycloak_home}}/modules/system/layers/keycloak/org/postgresql/main/module.xml"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    mode: 0750
  when: keycloak_ds_driver_url and
        keycloak_ds_driver_name and
        keycloak_ds_driver_module and
        keycloak_custom_driver

- name: Create management user
  command: "{{ wildfly_dir }}/bin/add-user-keycloak.sh -r master -u {{ keycloak_management_user }} -p {{ keycloak_management_password }}"
  become_user: "{{ wildfly_user }}"
  when: keycloak_management_user is defined and
        keycloak_management_password is defined
  ignore_errors: yes

- name: Create providers directory
  file:
    path: "{{wildfly_dir}}/providers"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    mode: 777
    state: directory

- name: Deploy SMS plugin
  copy: src={{keycloak_sms_provider_build}} dest="{{wildfly_dir}}/providers/" owner={{wildfly_user}} group={{wildfly_group}}

- name: Create sms-provider directory to store configuration
  file:
    path: "{{wildfly_dir}}/bin/sms-provider"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    mode: 750
    state: directory

- name: Deploy sms-provider templates
  copy: src={{keycloak_sms_provider_templates_src}} dest={{keycloak_sms_provider_templates_dest}} owner={{wildfly_user}} group={{wildfly_group}}

- name: Deploy sms-provider templates
  copy: src={{keycloak_sms_provider_templates_src}} dest={{keycloak_sms_provider_templates_dest}} owner={{wildfly_user}} group={{wildfly_group}}

- name: extarct Deploy sms-provider templates
  unarchive: src="{{keycloak_sms_provider_templates_dest}}/templates.tar.gz" dest={{keycloak_sms_provider_templates_dest}} copy=no owner={{wildfly_user}} group={{wildfly_group}}

- name: Create configuration file
  template:
    src: "templates/Msg91Creds.json.j2"
    dest: "{{ wildfly_dir }}/bin/sms-provider/Msg91Creds.json"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"

- name: start service
  become: yes
  command: /etc/init.d/keycloak start
  poll: 5
  async: 5
