user_home: /home/deployer
cassandra_repo: 'deb http://www.apache.org/dist/cassandra/debian 311x main'
cassandra_repo_key: 'https://www.apache.org/dist/cassandra/KEYS'
resource_crunch: "yes" # make this value yes if heap size should be quarter of the Server Memory when you are deploying multiple databases, else make this value no to have 50% of the value as per the best practice of cassandra
