---
# tasks file for keycloak

#- include: install.yml
- include: configure.yml

- include: driver.yml
  when: keycloak_ds_driver_url and
        keycloak_ds_driver_name and
        keycloak_ds_driver_module and
        keycloak_custom_driver

#- include: datasource.yml
#  when: keycloak_custom_ds != ""

- include: users.yml

- include: service.yml
  tags:
    - provision
