es_heap_size: 1500m
es_etc_cluster_name: sunbird-dev
es_etc_discovery_zen_minimum_master_nodes: 2
es_snapshot_host: "{{ groups['es-backup'][0] }}"
es_restore_host: "{{ groups['es-backup'][0] }}"
snapshot_base_path: application
