# Consumers to be on-boarded
kong_consumers:
  - username: api-management-test-user
    groups: "{{ kong_all_consumer_groups }}"
    state: present
    rate_limits: "{{ premium_consumer_rate_limits }}"
  - username: sunbird-integrator-test-user
    groups: "{{ integration_partner_groups }}"
    state: present
    credential_algorithm: "RS256"
    credential_rsa_public_key: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvknOmYAnTRS2BJCm0EXT\nqs3Zg3HPFyhwHIlWp2vwOo5rKLUBmNlSM91yy2vAr7A3wwg+HKe+k+b8XZEJAJyf\nlvtlbRkbuDNpxaqPVav6h7hfUT2RvJOIZn828JLtgYzsA92kD3Ef4YnQoX2FoNLn\noQL0B8WfHbVFkKTbSlz59MlEp74Wx39lTSXjFDYG0wrLiUMW7Eq8ECTEj9ombB+o\nVnBq0mgRNqywtxQlAiFFkuP2H7FATttcHi5PuF8vYMJtpj6PSHmdsMc++VdVE3Pw\n4rQ9s/WY2ThV80RecL5c7jSlfXTyLDTnR10ZNZnMCEzcZAKBSdiIlDmLoZ4852P6\ncwIDAQAB\n-----END PUBLIC KEY-----"
    credential_iss: "sunbird-integrator-test.org"
  - username: mobile_admin
    groups: "{{ mobile_admin_groups }}"
    print_credentials: true
    state: present
  - username: mobile_app
    groups: "{{ mobile_app_groups }}"
    state: present
  - username: mobile_device
    groups: "{{ mobile_device_groups }}"
    state: present
  - username: add-any-consumer-to-be-deleted
    state: absent
  - username: apekx-integrator-user
    groups: "{{ integration_partner_groups }}"
    state: absent
    credential_algorithm: "RS256"
    credential_rsa_public_key: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7PtN8+rUo1VnB0BQzEgE\ntaYgYTFk5fnfLB6djy/O0IGx59msT1/V92OwCXFRtXZgCJ/9YIqwprPh/MYcdtAv\nd8Rh/OFQHndwf+yT+3vm2S834hWrgmTNE3fTpgmbbbwm41dJQ2Nv/++SrY6UN+lJ\ncuF8WbizUWZxXHe8HFyIoi52JnBBHpCunXVlMgZL9NT6/hoz8DNfehqpRswveuCF\niW66UVN3MBzBvHEv+gMFyG20UvijdY5vtGYWo30/ExeiDesdGy1JC0fHpjW3FJqE\nBu+Q7Cy1AGFa0ZexLFaLKPspKSLwR0mgkzxV+5x9bhygDC8uXEA3ImuqtkdIXTYw\nUQIDAQAB\n-----END PUBLIC KEY-----"
    credential_iss: "apekx"
