# Common variables for all dev
env: dev
azure_storage_secret: "{{vault_azure_storage_secret}}"
azure_public_container: sunbird-content-dev # azure container name
azure_account_name: sunbirddevnewenv # azure storage account name

secrets_path: '{{inventory_dir}}/secrets/dp_secrets.yml'

#################### DP ##########################
ecosystem_user: ecosystem
ecosystem_group: ecosystem
zk_hosts: "127.0.0.1:2181"
kafka_conf_dir: /etc/kafka
kafka_data_dir: /var/kafka
kafka_group: kafka
kafka_user: kafka
kafka_log_dir: /var/log/kafka
kafka_upstart_conf: /etc/init/kafka.conf
kafka_systemd_service: /etc/systemd/system/kafka.service
zookeeper_systemd_service: /etc/systemd/system/zookeeper.service
kafka_auto_create_topics: "false"
kafka_log_retention_hours: 2400
monasca_log_level: ERROR
delete_topic_enable: "true"
zk_port: 2181
resourcemanager: "{{ groups['dp-yarn-master'][0] }}"
hadoop_version: 2.7.2
yarn_slaves:
  - "{{ groups['dp-yarn-slave'] }}"
yarn_slaves_master:
 - "{{ groups['dp-yarn'] }}"
monitor_yarn_url: "http://{{ resourcemanager }}:8088/ws/v1/cluster/apps?states=RUNNING"
yarn_am_container_memory_mb: 128
yarn_container_memory_mb: 128
telemetry_extractor_yarn_container_count: 2
telemetry_validator_yarn_container_count: 2
telemetry_de_duplication_yarn_container_count: 2
telemetry_router_yarn_container_count: 4
telemetry_reverse_search_yarn_container_count: 4
telemetry_object_de_normalization_yarn_container_count: 1
telemetry_es_indexer_yarn_container_count: 4
max_iteration_count_for_samza_job: 2
__yarn_host__: "{{ groups['dp-yarn-master'][0] }}"
__yarn_port__: 8000
search_service_endpoint: https://dev.ekstep.in/api/search/v2/search
yarn_es_hosts: "{{ groups['telemetry-search-cluster'] | join(',') }}"
env_name: dev
apt_cache_valid_time: 3600
cloud_store: azure
kafka_brokers: "{{groups['processing-cluster-kafka']|join(':9092,')}}:9092"
zookeepers: "{{groups['zookeeper']|join(':2181,')}}:2181"
# Ingestion cluster
ingestion_zookeepers: "{{ groups['processing-cluster-zookeepers']|join(':2181,')}}:2181"

processing_kafka_overriden_topics:
  - name: telemetry.raw
    retention_time: 172800000
    replication_factor: 1
  - name: telemetry.valid
    retention_time: 21600000
    replication_factor: 1
  - name: telemetry.unique
    retention_time: 172800000
    replication_factor: 1
  - name: telemetry.duplicate
    retention_time: 21600000
    replication_factor: 1
  - name: telemetry.sink
    retention_time: 21600000
    replication_factor: 1
  - name: telemetry.with_location
    retention_time: 86400000
    replication_factor: 1
  - name: telemetry.de_normalized
    retention_time: 21600000
    replication_factor: 1
  - name: telemetry.log
    retention_time: 21600000
    replication_factor: 1
  - name: analytics.job_queue
    retention_time: 86400000
    replication_factor: 1
  - name: learning.graph.events
    retention_time: 86400000
    replication_factor: 1
  - name: pipeline_metrics
    retention_time: 86400000
    replication_factor: 1
  - name: metrics
    retention_time: 604800000
    replication_factor: 1
  - name: learning.graph.events.fail
    retention_time: 1296000000
    replication_factor: 1
  - name: analytics_metrics
    retention_time: 21600000
    replication_factor: 1
  - name: learning.job.request
    retention_time: 86400000
    replication_factor: 1
  - name: learning.job.request.fail
    retention_time: 1296000000
    replication_factor: 1
  - name: learning.republish.job.request
    retention_time: 1296000000
    replication_factor: 1
  - name: telemetry.derived
    retention_time: 21600000
    replication_factor: 1
  # Error/Failed Topics
  - name: telemetry.failed
    retention_time: 86400000
    replication_factor: 1
  - name: telemetry.malformed
    retention_time: 21600000
    replication_factor: 1
  - name: telemetry.extractor.failed
    retention_time: 21600000
    replication_factor: 1
  - name: telemetry.indexer.failed
    retention_time: 21600000
    replication_factor: 1

telemetry_schema_directory: /etc/{{env}}/telemetry
telemetry_schema_path: /etc/{{env}}/telemetry/schemas
schema_repo_url: https://github.com/project-sunbird/sunbird-data-pipeline.git
delayInMilliSeconds: 60000
retryTimeInMilliSeconds: 10000
retry_backoff_base_in_seconds: 10
bypass_reverse_search: true
retry_limit: 4
retry_limit_enable: true
google_api_key: "123"
environment_id: 10000000
tr_secondary_route_events: "LOG,ERROR"
google_vision_tagging: false
language_url: http://{{ groups['learning1'][0] }}:8080/language-service
cassandra_host:  "{{ groups['cassandra'][0] }}"
cassandra_port: 9042
content_to_vec_url: http://{{ groups['analytics-api'][0] }}:9000/content-to-vec
es_port: 9200
default_channel: "01250894314817126443"

ssh_user: ecosystem
group: ecosystem

kibana_base_path: "/pipeline-dashboard"


################ LPA ###########################

analytics_user: analytics
analytics_group: analytics
azure_storage_account: sunbirddevnewenv
azure_storage_key: "{{azure_storage_account}}"
secor_azure_container_name: dev-data-store

analytics:
   home: /mount/data/analytics
   soft_path: /mount/data/analytics
   paths: ['/home/analytics/sbin', '/mount/data/analytics', '/mount/data/analytics/logs', '/mount/data/analytics/logs/services', '/mount/data/analytics/logs/data-products', '/mount/data/analytics/logs/api-service', '/mount/data/analytics/api', '/mount/data/analytics/tmp', '/mount/data/analytics/scripts/monitor-data', '/mount/data/analytics/models' ]
   scripts: ['model-config', 'replay-job', 'replay-updater', 'replay-utils', 'run-job', 'monitor-dp', 'generate-metrics', 'submit-job', 'start-jobmanager']

consumer_channel_cache_type: ConsumerChannel

analytics_user_home: /home/{{ analytics_user }}
sbin_path: "{{ analytics_user_home }}/sbin"
postgres:
  db_url: sunbirddevnewenv.postgres.database.azure.com #"{{ groups['postgres'][0] }}"
  db_username: analytics@sunbirddevnewenv #analytics
  db_name: analytics
  db_password: "{{vault_pgdb_password}}"
  db_table_name: sunbirddev_consumer_channel_mapping

metrics_search_params_bucket: "{{env}}-data-store"
log4j_appender_kafka_topic: "{{env}}.telemetry.backend"
default_channel_id: in.ekstep
channel_data_exhaust_bucket: telemetry-data-store

geo_location_city: "sunbirddev_geo_location_city"
geo_location_city_ipv4: "sunbirddev_geo_location_city_ipv4"

# Data products
data_exhaust_webhook_url: "https://hooks.slack.com/services/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"
data_exhaust_Channel: "sunbird-dp-dev-alerts"
data_exhaust_token: "xoxp-19320441927-104869600647-207667594868-6d8554b70e8f458a40c7453e47b7f61c"
data_exhaust_name: "dp-monitor"
straem_base_url: "https://sunbirdspikemedia-inct.streaming.media.azure.net"

# Secor vars
secor:
  properties: ['secor.azure', 'secor.common', 'secor', 'secor.partition', 'log4j']
  artifact_dir: /mount/secor
  s3:
    bucket: "dev-data-store"
    #aws_key: "{{vault_aws_key}}"
    #aws_secret: "{{vault_aws_secret}}"
  azure:
    account_name: "dev-data-store"
    account_key: "{{ vault_azure_account_key }}"
    container_name: "sunbirddevnewenv"
  paths: ['/mount/secor', '/mount/secor/reports', '/mount/secor/logs', '/home/analytics/sbin', '/mount/data/analytics']
  channel: "#sunbird-dp-dev-alerts"

# postgres
# list of databases to be created
postgresql_databases:
  - name: analytics
    owner: analytics
postgresql_users:
  - name: analytics
    password: "{{vault_pgdb_password}}"

postgres_address_space: 0.0.0.0/0 # Postgres trust address space
lp_composite_search: http://11.2.3.30:9200 # Composite Cluster ip of LP
lp_search: http://11.2.4.16:9000

# Values to be depricated ??

# lp_bolt_url: bolt://{{ groups['learning-neo4j-node1'][0] }}:7687
# lp_bolt_read_url: bolt://{{ groups['learning-neo4j-node1'][0] }}:7687
# lp_bolt_write_url: bolt://{{ groups['learning-neo4j-node1'][0] }}:7687
# lp_url: http://{{ groups['learning1'][0] }}:8080/learning-service
# lp_tmpfile_location: /tmp
