---
- name: upload files and folders - uploading {{ oss_bucket_name  }}/{{ object_prefix }}
  shell: oci os object bulk-upload -bn {{oss_bucket_name}} --prefix {{object_prefix}} --src-dir {{local_file_or_folder_path}} --overwrite --content-type auto
  async: 1800
  poll: 0
