---
- name: Create the keys directory in case user is overriding the private_key_path
  file:
    path: "{{chart_path}}/keys"
    state: directory
    mode: 0755

- name: Copy keys directory to chart path
  vars:
    private_key_path: "{{private_key_path | regex_replace('^\\/|\\/$', '')}}"
  copy: "src={{inventory_dir}}{{private_key_path}}{{private_key_prefix}}{{item}} dest={{chart_path}}/keys/"
  with_sequence: start={{private_key_sign_start}} end={{private_key_sign_start|int + private_key_sign_end|int - 1}} stride={{private_key_sign_incr}}
  when: (private_key_sign_start|int + private_key_sign_end|int - 1) > 0
 
