---
- name: Generate Public Keys for private keys
  vars:
    private_key_path: "{{private_key_path | regex_replace('^\\/|\\/$', '')}}"
  shell: "openssl rsa -in {{ lookup('fileglob', '{{inventory_dir}}/{{private_key_path}}/{{private_key_prefix}}{{item}}') }} -outform PEM -pubout -out {{inventory_dir}}/{{private_key_path | regex_replace('^\\/|\\/$', '')}}/{{private_key_prefix}}{{item}}"
  with_sequence: start={{private_key_sign_start}} end={{private_key_sign_end}} stride={{private_key_sign_incr}}
