version: '3'

services:
  kong:
    image: sunbird/kong:{{kong_version}}
    env_file:
      /home/deployer/env/api-manager.env
    ports:
      - 8000:8000
      - 8001:8001
    networks:
      - api-manager_default
      - application_default
    deploy:
      replicas: {{ kong_replicas }}
      resources:
        reservations:
          memory: "{{ kong_reservation_memory }}"
        limits:
          memory: "{{ kong_limit_memory }}"
      update_config:
        parallelism: 1
        delay: 30s
    healthcheck:
      test: curl -f http://localhost:8001/status || exit 1
      interval: 10s
      timeout: 20s
      retries: 10

  echo:
    image: "{{hub_org}}/{{echo_server_image_name}}:{{echo_server_image_tag}}"
    networks:
      - api-manager_default
    ports:
      - 9595:9595
    deploy:
      replicas: {{ echo_service_replicas }}
      resources:
        reservations:
          memory: "{{ echo_service_reservation_memory }}"
        limits:
          memory: "{{ echo_service_limit_memory }}"
      update_config:
        parallelism: 1
        delay: 5s
    healthcheck:
      test: wget -q -s http://localhost:9595/hello || exit 1
      interval: 5s
      timeout: 5s
      retries: 3

networks:
  api-manager_default:
    external: true
  application_default:
    external: true
