prometheus_reservation_memory: 1G
prometheus_limit_memory: 1G
prometheus_storage_retention_time: 90d

alertmanager_reservation_memory: 100M
alertmanager_limit_memory: 100M

node_exporter_reservation_memory: 16M
node_exporter_limit_memory: 32M

cadvisor_reservation_memory: 80M
cadvisor_limit_memory: 200M

elasticsearch_exporter_reservation_memory: 8M
elasticsearch_exporter_limit_memory: 24M

postgres_exporter_reservation_memory: 16M
postgres_exporter_limit_memory: 32M

statsd_exporter_reservation_memory: 8M
statsd_exporter_limit_memory: 16M

blackbox_exporter_reservation_memory: 16M
blackbox_exporter_limit_memory: 32M

jsonpath_exporter_reservation_memory: 32M
jsonpath_exporter_limit_memory: 64M

azure_blob_exporter_reservation_memory: 16M
azure_blob_exporter_limit_memory: 64M

container_cpu_usage_percentage_theshold: 90
container_memory_usage_percentage_theshold: 90

# Override this at environment level
expected_minimum_logs_per_minute: 0
server_side_http_errors_threshold_percentage: 1

# Defaults to 1 day (24 hours) with 1 hour extra for backup process to complete
expected_data_backup_interval_in_minutes: "{{ 25 * 60 }}"

# Defaults to 1 day (24 hours) with 1 hour extra for snapshot process to complete
expected_elasticsearch_snapshot_interval_in_minutes: "{{ 25 * 60 }}"

# Defaults to 1KB. Good enough to catch errors mentioned in https://about.gitlab.com/2017/02/01/gitlab-dot-com-database-incident/
expected_data_backup_size_in_bytes: 1024

enable_postgres_availability_check: true

enable_scraping_docker_metrics: false
docker_metrics_port: "2377"

kong_cluster_expected_number_of_nodes: "{{ kong_replicas | default(1) }}"

monitor_config_files_dest_dir: /opt/docker/stacks/monitor/config

docker_service_replicas_exporter_version: v0.0.3
docker_service_replicas_exporter_name: docker-service-replicas-exporter

monitor_config_templates:
  - prometheus.yml
  - alertmanagerconfig.yml
  - blackboxconfig.yml
  - statsd_mapping.yml
  - kong_cluster_exporter_config.yml
  - alertrules.nodes.yml
  - alertrules.task.yml
  - alertrules.kong.yml

monitor_config_templates_postgres:
  - postgresmasterqueries.yml
  - postgresslavequeries.yml

devops_alerts_mailing_list: "{{ alerts_mailing_list }}"
devops_alerts_mailing_severity_filter: "{{ alerts_mailing_severity_filter }}"
druid_alerts_mailing_severity_filter: "{{ druid_alerts_mailing_severity_filter }}"

service_teams:
  - team: devops_team
    alerts_mailing_list: "{{ devops_alerts_mailing_list }}"
    severity_mailing_filter: "{{ devops_alerts_mailing_severity_filter }}"
    services:
      - monitor_.*
      - monit
      - logger_.*
      - proxy_.*
  - team: app_team
    alerts_mailing_list: "{{ app_alerts_mailing_list | default(devops_alerts_mailing_list) }}"
    severity_mailing_filter: "{{ devops_alerts_mailing_severity_filter }}"
    services:
      - learner-service
      - lms-service
      - content-service
      - player_player
      - cassandra
      - composite_search
      - analytics-api    
  - team: keycloak_team
    alerts_mailing_list: "{{ keycloak_alerts_mailing_list | default(devops_alerts_mailing_list)}}"
    severity_mailing_filter: "{{ devops_alerts_mailing_severity_filter }}"
    services:
      - keycloak    
  - team: api_manager_team
    alerts_mailing_list: "{{ api_manager_alerts_mailing_list | default(devops_alerts_mailing_list)}}"
    severity_mailing_filter: "{{ devops_alerts_mailing_severity_filter }}"
    services:
      - api-manager_.*
      - adminutil_.*    
  - team: site_team
    alerts_mailing_list: "{{ site_alerts_mailing_list | default(devops_alerts_mailing_list)}}"
    severity_mailing_filter: "{{ devops_alerts_mailing_severity_filter }}"
    services:
      - sunbird_static_site    
  - team: druid
    alerts_mailing_list: "{{ druid_alerts_mailing_list | default(devops_alerts_mailing_list)}}"
    severity_mailing_filter: "{{ devops_alerts_mailing_severity_filter }}, {{ druid_alerts_mailing_severity_filter }}"
    services:
      - druidzookeeper
      - druidpostgres
      - overlord
      - coordinator
      - historical
      - broker
      - middlemanager    

service_blackbox_checks:
  - service_name: 'adminutil_adminutil'
    probe_module: http_2xx
    targets:
      - http://adminutil_adminutil:4000/health
  - service_name: 'player_player'
    probe_module: http_2xx
    targets:
      - http://player_player:3000/health
  - service_name: 'learner-service'
    probe_module: http_2xx
    targets:
      - http://learner-service:9000/health
  - service_name: 'api-manager_kong'
    probe_module: http_2xx
    targets:
      - http://api-manager_kong:8001/status
  - service_name: 'api-manager_echo'
    probe_module: http_2xx
    targets:
      - http://api-manager_echo:9595/hello
  - service_name: 'content-service'
    probe_module: http_2xx
    targets:
      - http://content-service:5000/service/health
  - service_name: 'telemetry-service'
    probe_module: http_2xx
    targets:
      - http://telemetry-service:9001/health
  - service_name: 'monit'
    probe_module: http_2xx
    targets:
      - "http://{{ groups['swarm-bootstrap-manager'][0] }}:2812"
  - service_name: 'logger_oauth'
    probe_module: http_2xx
    targets:
            - "http://oauth:4111/robots.txt"

prometheus_route_prefix: prometheus
prometheus_web_external_url: "{{proto}}://{{api__host}}:9090/{{ prometheus_route_prefix }}"

prometheus_alertmanager_route_prefix: alertmanager
prometheus_alertmanager_web_external_url: "{{proto}}://{{api__host}}:9093/{{ prometheus_alertmanager_route_prefix }}"

postgres_exporter_password:
postgres_exporter_postgres_port: 5432
postgres_exporter_user: postgres_exporter

root_group: root
root_owner: root
backup_storage_name: prometheus_backup

docker_service_replicas_memory_limit: 256MB
prometheus_mount_point: "/root/dockerdata/prometheus/data/"

#################################################### Monitoring limits ################################################
container_cpu_usage_percentage_threshold_Warning: 70
container_cpu_usage_percentage_threshold_Critical: 85
container_cpu_usage_percentage_threshold_Fatal: 95

container_memory_usage_percentage_threshold_Warning: 70
container_memory_usage_percentage_threshold_Critical: 85
container_memory_usage_percentage_threshold_Fatal: 95

node_cpu_usage_percentage_threshold_Warning: 70
node_cpu_usage_percentage_threshold_Critical: 85
node_cpu_usage_percentage_threshold_Fatal: 95

node_memory_usage_percentage_threshold_Warning: 70
node_memory_usage_percentage_threshold_Critical: 85
node_memory_usage_percentage_threshold_Fatal: 95

node_load_avg_threshold_Warning: 85
node_load_avg_threshold_Critical: 95
node_load_avg_threshold_Fatal: 120

node_disk_usage_percentage_threshold_Warning: 70
node_disk_usage_percentage_threshold_Critical: 85
node_disk_usage_percentage_threshold_Fatal: 95

postgres_number_of_connections_Warning: 100
postgres_number_of_connections_Critical: 110
postgres_number_of_connections_Fatal: 130

elasticsearch_filesystem_data_remaining_threshold_Warning: 20
elasticsearch_filesystem_data_remaining_threshold_Critical: 15
elasticsearch_filesystem_data_remaining_threshold_Fatal: 10
