---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}echo
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.apimanagerecho.replicaCount }}
  strategy:
     type: {{ .Values.apimanagerecho.strategy.type }}
     rollingUpdate:
       maxSurge: {{ .Values.apimanagerecho.strategy.maxSurge }}
       maxUnavailable: {{ .Values.apimanagerecho.strategy.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}echo
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: {{ .Chart.Name }}echo
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagepullsecrets }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.dockerhub }}/{{ .Values.apimanagerecho.repository }}:{{ .Values.apimanagerecho.image_tag }}"
        resources:
          requests:
            cpu: {{ quote .Values.apimanagerecho.resources.cpu }}
            memory: {{ quote .Values.apimanagerecho.resources.memory }}
        ports:
        - containerPort: {{ .Values.apimanagerecho.network.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}echo
spec:
  ports:
  - name: http-{{ .Chart.Name }}echo
    protocol: TCP
    port: {{ .Values.apimanagerecho.network.targetport }}
  selector:
    app: {{ .Chart.Name }}echo
