---
- name: Remove actor service
  shell: "docker service rm actor-service"
  ignore_errors: yes

- name: Deploy actor service
  shell: "docker service create --with-registry-auth --replicas {{ actor_replicas }} -p 8088:8088 --name actor-service --hostname actor-service --reserve-memory {{ actor_reservation_memory }} --limit-memory {{ actor_limit_memory }}  --network application_default --env-file /home/deployer/env/sunbird_actor-service.env {{hub_org}}/{{image_name}}:{{image_tag}}"
  args:
    chdir: /home/deployer/stack
