---
- name: Remove config service
  shell: "docker service rm config-service"
  ignore_errors: yes

- name: Deploy config service
  shell: "docker service create --with-registry-auth --replicas {{ config_replicas }} -p 6000:8080  --name config-service --hostname config-service --reserve-memory {{ config_reservation_memory }} --limit-memory {{ config_limit_memory }} --network application_default --env-file /home/deployer/env/sunbird_config-service.env  {{hub_org}}/{{image_name}}:{{image_tag}}" 
  args:
    chdir: /home/deployer/stack
