---
- name: Remove learning service
  shell: "docker service rm learning-service"
  ignore_errors: yes

- name: Deploy learning service
  shell: "docker service create --with-registry-auth --replicas {{ learner_replicas }} -p 9000:9696  --name learning-service --hostname learning-service --reserve-memory {{ learner_reservation_memory }} --limit-memory {{ learner_limit_memory }} --limit-cpu {{ learner_limit_cpu }} --reserve-cpu {{ learner_reservation_cpu }} --health-cmd 'wget -qO- learning-service:9000/health || exit 1' --health-timeout 3s --health-retries 3  --network application_default --env-file /home/deployer/env/sunbird_learning-service.env  {{hub_org}}/{{image_name}}:{{image_tag}}"
  args:
    chdir: /home/deployer/stack