---
- name: Remove lms service
  shell: "docker service rm lms-service"
  ignore_errors: yes

- name: Deploy lms service
  shell: "docker service create --with-registry-auth --replicas {{ lms_service_replicas }} -p 9005:9000  --name lms-service --hostname lms-service --reserve-memory {{ lms_service_reservation_memory }} --limit-memory {{ lms_service_limit_memory }} --limit-cpu {{ lms_service_limit_cpu }} --reserve-cpu {{ lms_service_reservation_cpu }} --health-cmd 'wget -qO- lms-service:9000/service/health || exit 1' --health-timeout 10s --health-retries 5  --network application_default --env JAVA_OPTIONS={{ lms_java_mem_limit }} --env-file /home/deployer/env/sunbird_lms-service.env  {{hub_org}}/{{image_name}}:{{image_tag}}"
  args:
    chdir: /home/deployer/stack
