---
  - include: common.yml

  - include: service_stack.yml
    when: deploy_stack is defined


  - include: actor_service.yml
    when: deploy_actor is defined

  - include: learner_service.yml
    when: deploy_learner is defined
