---
  - include: common.yml

  - include: service_stack.yml
    when: deploy_stack is defined

  - include: learner_service.yml
    when: deploy_learner is defined
  
  - include: lms_service.yml
    when: deploy_lms is defined

  - include: enc_service.yml
    when: deploy_enc is defined

  - include: user_org_service.yml
    when: deploy_user_org is defined

  - include: cert_service.yml
    when: deploy_cert is defined

  - include: cert_registry_service.yml
    when: cert_registry_service is defined

  - include: notification_service.yml
    when: deploy_notification is defined

  - include: knowledge-mw-service.yml
    when: deploy_knowledge_mw is defined

  - include: telemetry_service.yml
    when: deploy_telemetry is defined

  - include: telemetry_logstash.yml
    when: deploy_telemetry_logstash is defined

  - include: config_service.yml
    when: deploy_config is defined

  - include: telemetry_logstash_datapipeline.yml
    when: deploy_telemetry_logstash_datapipeline is defined

  - include: content-service.yml
    when: deploy_content is defined

  - include: assessment-service.yml
    when: deploy_assessment is defined

  - include: druid_proxy_api_service.yml
    when: deploy_druid_proxy_api is defined

  - include: print-service.yml
    when: deploy_print is defined

  - include: report-service.yml
    when: deploy_report is defined

  - include: search-service.yml
    when: deploy_search is defined

  - include: taxonomy-service.yml
    when: deploy_taxonomy is defined

  - include: restart_private_proxy.yml
