---
- name: Remove notification service
  shell: "docker service rm notification-service"
  ignore_errors: yes

- name: Deploy notification service
  shell: "docker service create --with-registry-auth --replicas {{ notification_replicas }} -p 9012:9000  --name notification-service --hostname notification-service --limit-memory {{ notification_limit_memory }} --limit-cpu {{ notification_limit_cpu }}  --network application_default --env-file /home/deployer/env/sunbird_notification-service.env  {{hub_org}}/{{image_name}}:{{image_tag}}"
