- name: Install dependencies for Ubuntu
  apt:
    name: '{{ item }}'
    state: installed
    force: yes
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - linux-image-extra-virtual
  become: true

- name: Add key
  raw: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: Add docker repository
  become: true
  lineinfile:
    line: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    dest: /etc/apt/sources.list.d/docker.list
    state: present
    create: yes
  notify: restart docker

- shell: docker info
  changed_when: False
  register: docker_info

- shell: "docker swarm init --advertise-addr {{inventory_hostname}}"
  when: "docker_info.stdout.find('Swarm: active') == -1"

- name: Install jq
  apt: name=jq state=present
  become: yes

- name: Create networks
  shell: "docker network create --subnet {{subnet_range}} --driver overlay {{subnet_name}}"
  ignore_errors: true
  run_once: true
