# Please change memory requirements if heap_size is changed
logger_logstash_heap_size: 512M
logger_logstash_replicas: 2
logger_logstash_reservation_memory: 512M
logger_logstash_limit_memory: 750M
logger_logspout_reservation_memory: 75M
logger_logspout_limit_memory: 75M
logger_logstash_reservation_memory: 1024M
logger_logstash_limit_memory: 1024M
