# Please change memory requirements if heap_size is changed
logger_logstash_heap_size: 512M
logger_logstash_replicas: 2
logger_logstash_reservation_memory: 512M
logger_logstash_limit_memory: 750M

logger_kibana_reservation_memory: 750M
logger_kibana_limit_memory: 750M
kibana_image: kibana:4.6

logger_logspout_reservation_memory: 75M
logger_logspout_limit_memory: 75M

logger_oauth_reservation_memory: 32M
logger_oauth_limit_memory: 32M

kibana_oauth_authenticated_email_domains: []
kibana_oauth_authenticated_email_ids: []
logger_logstash_reservation_memory: 1024M
logger_logstash_limit_memory: 1024M
