---
- name: Set azure snapshot for the first time
  uri:
    url: "http://{{ es_restore_host }}:9200/_snapshot/azurebackup"
    method: PUT
    body: "{{ snapshot_create_request_body | to_json }}"
    headers:
      Content-Type: "application/json"

- debug:
    var: snapshot_base_path

- name: Restore ES from Azure backup
  uri:
    url: "http://{{ es_restore_host }}:9200/_snapshot/azurebackup/{{snapshot_number}}/_restore"
    method: POST

- name: "Wait for restore to be completed"
  uri:
    url: "http://{{ es_restore_host }}:9200/_snapshot/azurebackup/{{snapshot_number}}/_status"
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  register: result
  until: result.json.snapshots[0].state == 'SUCCESS'
  retries: 1200
  delay: 10
