groups:
- name: alertrules.kong
  rules:
  - alert: kong_cluster_unhealthy_FATAL
    expr: kong_cluster_alive_nodes != {{ kong_cluster_expected_number_of_nodes }}
    for: 5m
    labels:
      severity: FATAL
    annotations:
      description: 'Number of live nodes : {% raw %}{{$value}}{% endraw %} not equal to : {{ kong_cluster_expected_number_of_nodes }}'
      summary: 'Kong cluster is unhealthy'
