groups:
- name: alertrules.nodes
  rules:
  - alert: high_cpu_usage_on_node_WARNING
    expr: sum by(nodename) (rate(process_cpu_seconds_total[5m]) * on(instance) group_left(nodename) node_uname_info * 100) >= 70  and sum by(nodename) (rate(process_cpu_seconds_total[5m]) * on(instance) group_left(nodename) node_uname_info * 100) < 85 
    for: 5m
    labels:
      severity: WARNING
    annotations:
      description: '{% raw %}{{ $labels.nodename }}{% endraw %} ({% raw %}{{ $labels.host }}{% endraw %}) is using a LOT of CPU. CPU usage is {% raw %}{{ humanize $value}}{% endraw %}%.'
      summary: 'HIGH CPU USAGE WARNING ON {% raw %}{{ $labels.nodename }}{% endraw %}'
  - alert: high_cpu_usage_on_node_CRITICAL
    expr: sum by(nodename) (rate(process_cpu_seconds_total[5m]) * on(instance) group_left(nodename) node_uname_info * 100) >= 85  and sum by(nodename) (rate(process_cpu_seconds_total[5m]) * on(instance) group_left(nodename) node_uname_info * 100) < 95 
    for: 5m
    labels:
      severity: CRITICAL
    annotations:
      description: '{% raw %}{{ $labels.nodename }}{% endraw %} ({% raw %}{{ $labels.host }}{% endraw %}) is using a LOT of CPU. CPU usage is {% raw %}{{ humanize $value}}{% endraw %}%.'
      summary: 'HIGH CPU USAGE WARNING ON {% raw %}{{ $labels.nodename }}{% endraw %}'
  - alert: high_cpu_usage_on_node_FATAL
    expr: sum by(nodename) (rate(process_cpu_seconds_total[5m]) * on(instance) group_left(nodename) node_uname_info * 100) >= 95 
    for: 5m
    labels:
      severity: FATAL
    annotations:
      description: '{% raw %}{{ $labels.nodename }}{% endraw %} ({% raw %}{{ $labels.host }}{% endraw %}) is using a LOT of CPU. CPU usage is {% raw %}{{ humanize $value}}{% endraw %}%.'
      summary: 'HIGH CPU USAGE WARNING ON {% raw %}{{ $labels.nodename }}{% endraw %}'
  - alert: high_memory_usage_on_node_WARNING
    expr: sum by(nodename) (((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * on(instance) group_left(nodename) node_uname_info * 100) >= 70 and (((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * on(instance) group_left(nodename) node_uname_info * 100) < 85
    for: 5m
    labels:
      severity: WARNING
    annotations:
      description: '{% raw %}{{ $labels.nodename }}{% endraw %} ({% raw %}{{ $labels.host }}{% endraw %}) is using a LOT of MEMORY. MEMORY usage is over {% raw %}{{ humanize $value}}{% endraw %}.'
      summary: 'HIGH MEMORY USAGE WARNING TASK ON {% raw %}{{ $labels.nodename }}{% endraw %}'
  - alert: high_memory_usage_on_node_CRITICAL
    expr: sum by(nodename) (((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * on(instance) group_left(nodename) node_uname_info * 100) >= 85 and (((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * on(instance) group_left(nodename) node_uname_info * 100) < 95
    for: 5m
    labels:
      severity: CRITICAL
    annotations:
      description: '{% raw %}{{ $labels.nodename }}{% endraw %} ({% raw %}{{ $labels.host }}{% endraw %}) is using a LOT of MEMORY. MEMORY usage is over {% raw %}{{ humanize $value}}{% endraw %}.'
      summary: 'HIGH MEMORY USAGE WARNING TASK ON {% raw %}{{ $labels.nodename }}{% endraw %}'
  - alert: high_memory_usage_on_node_FATAL
    expr: sum by(nodename) (((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * on(instance) group_left(nodename) node_uname_info * 100) >= 95
    for: 5m
    labels:
      severity: FATAL
    annotations:
      description: '{% raw %}{{ $labels.nodename }}{% endraw %} ({% raw %}{{ $labels.host }}{% endraw %}) is using a LOT of MEMORY. MEMORY usage is over {% raw %}{{ humanize $value}}{% endraw %}.'
      summary: 'HIGH MEMORY USAGE WARNING TASK ON {% raw %}{{ $labels.nodename }}{% endraw %}'
  - alert: high_load_on_node_WARNING
    expr: sum by(nodename) ((node_load1 / count without(cpu, mode) (node_cpu_seconds_total{mode="system"})) * on(instance) group_left(nodename) node_uname_info * 100) >= 85 and ((node_load1 / count without(cpu, mode) (node_cpu_seconds_total{mode="system"})) * on(instance) group_left(nodename) node_uname_info * 100) < 95
    for: 5m
    labels:
      severity: WARNING
    annotations:
      description: '{% raw %}{{ $labels.nodename }}{% endraw %} ({% raw %}{{ $labels.host }}{% endraw %}) has a high load average. Load average is {% raw %}{{ $value }}{% endraw %}%.'
      summary: 'HIGH LOAD AVERAGE WARNING ON {% raw %}{{ $labels.nodename }}{% endraw %}'
  - alert: high_load_on_node_CRITICAL
    expr: sum by(nodename) ((node_load1 / count without(cpu, mode) (node_cpu_seconds_total{mode="system"})) * on(instance) group_left(nodename) node_uname_info * 100) >= 95 and ((node_load1 / count without(cpu, mode) (node_cpu_seconds_total{mode="system"})) * on(instance) group_left(nodename) node_uname_info * 100) < 120
    for: 5m
    labels:
      severity: CRITICAL
    annotations:
      description: '{% raw %}{{ $labels.nodename }}{% endraw %} ({% raw %}{{ $labels.host }}{% endraw %}) has a high load average. Load average is {% raw %}{{ $value }}{% endraw %}%.'
      summary: 'HIGH LOAD AVERAGE WARNING ON {% raw %}{{ $labels.nodename }}{% endraw %}'
  - alert: high_load_on_node_FATAL
    expr: sum by(nodename) ((node_load1 / count without(cpu, mode) (node_cpu_seconds_total{mode="system"})) * on(instance) group_left(nodename) node_uname_info * 100) >= 120
    for: 5m
    labels:
      severity: FATAL
    annotations:
      description: '{% raw %}{{ $labels.nodename }}{% endraw %} ({% raw %}{{ $labels.host }}{% endraw %}) has a high load average. Load average is {% raw %}{{ $value }}{% endraw %}%.'
      summary: 'HIGH LOAD AVERAGE WARNING ON {% raw %}{{ $labels.nodename }}{% endraw %}'
  - alert: monitoring_service_down_FATAL
    expr: up == 0
    for: 5m
    labels:
      severity: FATAL
    annotations:
      description: 'The monitoring service {% raw %}{{ $labels.job }}{% endraw %} is down.'
      summary: 'MONITORING SERVICE DOWN WARNING: NODE {% raw %}{{ $labels.host }}{% endraw %}'
  - alert: node_running_out_of_disk_space_WARNING
    expr: sum by(nodename) ((node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) * 100 / node_filesystem_size_bytes{mountpoint="/"} * on(instance) group_left(nodename) node_uname_info) >= 70 and ((node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) * 100 / node_filesystem_size_bytes{mountpoint="/"} * on(instance) group_left(nodename) node_uname_info) < 85
    for: 5m
    labels:
      severity: WARNING
    annotations:
      description: 'More than 70% of disk used. Disk usage is {% raw %}{{ humanize $value }}{% endraw %}%'
      summary: 'LOW DISK SPACE WARING: NODE {% raw %}{{ $labels.nodename }}{% endraw %}'
  - alert: node_running_out_of_disk_space_CRITICAL
    expr: sum by(nodename) ((node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) * 100 / node_filesystem_size_bytes{mountpoint="/"} * on(instance) group_left(nodename) node_uname_info) >= 85 and ((node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) * 100 / node_filesystem_size_bytes{mountpoint="/"} * on(instance) group_left(nodename) node_uname_info) < 95
    for: 5m
    labels:
      severity: CRITICAL
    annotations:
      description: 'More than 85% of disk used. Disk usage is {% raw %}{{ humanize $value }}{% endraw %}%'
      summary: 'LOW DISK SPACE WARING: NODE {% raw %}{{ $labels.nodename }}{% endraw %}'
  - alert: node_running_out_of_disk_space_WARNING
    expr: sum by(nodename) ((node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) * 100 / node_filesystem_size_bytes{mountpoint="/"} * on(instance) group_left(nodename) node_uname_info) >= 95
    for: 5m
    labels:
      severity: FATAL
    annotations:
      description: 'More than 95% of disk used. Disk usage is {% raw %}{{ humanize $value }}{% endraw %}%'
      summary: 'LOW DISK SPACE WARING: NODE {% raw %}{{ $labels.nodename }}{% endraw %}'
