---

- name: Ensure stack directory exists
  file:
    path: /home/deployer/stack
    state: directory
    owner: root
    group: root

- name: Ensure config directory exists
  file:
    path: /home/deployer/config
    state: directory
    owner: root
    group: root

- name: Save stack file
  template: src=stack-logger.yml dest=/home/deployer/stack/logger.yml mode=0644

- name: Save logstash config
  template: src=logstash.conf dest=/home/deployer/config/logstash.conf mode=0644

- name: Save kibana config
  template: src=kibana.yml dest=/home/deployer/config/kibana.yml mode=0644

- name: Save authenticated email file
  template: src=authenticated_email.txt dest=/home/deployer/config/authenticated_email.txt mode=0644

- name: Remove proxy stack
  shell: "docker stack rm logger"
  ignore_errors: yes

- name: Remove old logstash docker config
  shell: "docker config rm logstash.conf"
  ignore_errors: yes

- name: Remove old kibana docker config
  shell: "docker config rm kibana.yml"
  ignore_errors: yes

- name: Remove old authenticated email docker config
  shell: "docker config rm authenticated_email_kibana_oauth"
  ignore_errors: yes

- name: Save logstash config as docker config
  shell: "docker config create logstash.conf /home/deployer/config/logstash.conf"

- name: Save kibana config as docker config
  shell: "docker config create kibana.yml /home/deployer/config/kibana.yml"

- name: Save authenticated emails as docker config
  shell: "docker config create authenticated_email_kibana_oauth /home/deployer/config/authenticated_email.txt"

- name: Deploy stack
  shell: "docker stack deploy -c logger.yml logger"
  args:
    chdir: /home/deployer/stack
