---
kong_admin_api_url: "http://localhost:8001"

mobile_admin_groups:
  - mobileAdmin

mobile_app_groups:
  - mobileApp

mobile_device_groups:
  - contentUser
  - courseUser
  - appAdmin
  - configUser
  - publicUser
  - userAdmin

integration_partner_groups:
  - echoUser
  - orgAdmin
  - orgUser
  - userAdmin
  - publicUser

implementaion_user_groups:
  - contentAdmin
  - contentUser
  - userAdmin
  - publicUser
  - orgAdmin
  - orgUser

# List all consumer groups in group_vars
kong_all_consumer_groups:
  - appAdmin
  - contentAdmin
  - contentUser
  - courseAdmin
  - courseUser
  - echoUser
  - mobileAdmin
  - mobileApp
  - noteAdmin
  - noteUser
  - orgAdmin
  - orgUser
  - publicUser
  - userAdmin
  - configUser

# List the consumers need to be present as state: present
# List the consumers need to be absent as state: absent
# This role will not update / delete consumers not listed here
kong_consumers:
  - username: api-management-test-user
    groups: "{{ kong_all_consumer_groups }}"
    state: present
  - username: add-any-consumer-to-be-deleted
    state: absent
  - username: player
    groups: "{{ kong_all_consumer_groups }}"
    state: present
    rate_limits: "{{ premium_consumer_rate_limits }}"
  - username: mobile_admin
    groups: "{{ mobile_admin_groups }}"
    print_credentials: true
    state: present
  - username: mobile_app
    groups: "{{ mobile_app_groups }}"
    state: present
  - username: mobile_device
    groups: "{{ mobile_device_groups }}"
    state: present