---
kong_admin_api_url: "http://{{kong_host}}:8001"

mobile_admin_groups:
  - mobileSuperAdmin

mobile_app_groups:
  - mobileAdmin

potal_app_groups:
  - portalAdmin

mobile_device_groups:
  - appAccess
  - certificateAccess
  - contentAccess
  - courseAccess
  - deviceCreate
  - dialcodeAccess
  - locationAccess
  - orgAccess
  - ssoCreate
  - telemetryCreate
  - userAccess
  - userTempAdmin
  - userUpdate
  - contentTempAccess
  - groupCreate
  - groupUpdate
  - groupAccess
  - groupAdmin
  - refreshTokenCreate
  - discussionAccess

kong_all_consumer_groups:
  - announcementAccess
  - appAccess
  - appAdmin
  - appUpdate
  - badgeAccess
  - badgeAdmin
  - badgeCreate
  - badgeUpdate
  - certificateAccess
  - certificateAdmin
  - certificateCreate
  - certificateUpdate
  - channelAccess
  - channelCreate
  - channelUpdate
  - contentAccess
  - contentAdmin
  - contentCreate
  - contentUpdate
  - courseAccess
  - courseAdmin
  - courseCreate
  - courseUpdate
  - deviceCreate
  - dialcodeAccess
  - dialcodeAdmin
  - dialcodeCreate
  - dialcodeUpdate
  - locationAccess
  - noteAccess
  - noteAdmin
  - noteCreate
  - noteUpdate
  - objectAccess
  - orgAccess
  - orgCreate
  - pageAccess
  - pluginAccess
  - reportsAccess
  - reportsAdmin
  - reportsCreate
  - reportsUpdate
  - ssoCreate
  - userAccess
  - userAdmin
  - userCreate
  - userTempAdmin
  - userUpdate
  - groupCreate
  - groupUpdate
  - groupAccess
  - groupAdmin
  - dataAccess
  - druidReportCreate
  - druidReportAdmin
  - dataCreate
  - frameworkAccess

kong_consumers:
  - username: api-admin
    groups: "{{ kong_all_consumer_groups }}"
    state: present
  - username: mobile_admin
    groups: "{{ mobile_admin_groups }}"
    print_credentials: true
    state: present
  - username: mobile_app
    groups: "{{ mobile_app_groups }}"
    state: present
  - username: mobile_device
    groups: "{{ mobile_device_groups }}"
    state: present
  - username: mobile_devicev2
    groups: "{{ mobile_device_groups }}"
    state: present
  - username: portal_app
    groups: "{{ potal_app_groups }}"
    state: present
  - username: portalv2
    groups: "{{ kong_all_consumer_groups }}"
    state: present
