---
kong_admin_api_url: "http://{{kong_host}}:8001"

mobile_admin_groups:
  - mobileSuperAdmin

mobile_app_groups:
  - mobileAdmin

mobile_device_groups:
  - appAccess
  - certificateAccess
  - contentAccess
  - courseAccess
  - deviceCreate
  - dialcodeAccess
  - locationAccess
  - orgAccess
  - ssoCreate
  - telemetryCreate
  - userAccess
  - userTempAdmin
  - userUpdate

kong_all_consumer_groups:
  - announcementAccess
  - appAcces
  - appAccess
  - appAdmin
  - appCreate
  - appUpdate
  - badgeAccess
  - badgeAdmin
  - badgeCreate
  - badgeUpdate
  - certificateAccess
  - certificateCreate
  - certificateUpdate
  - channelAccess
  - channelAdmin
  - channelCreate
  - channelUpdate
  - contentAccess
  - contentAdmin
  - contentCreate
  - contentUpdate
  - courseAccess
  - courseAdmin
  - courseCreate
  - courseUpdate
  - deviceCreate
  - dialcodeAccess
  - dialcodeAdmin
  - dialcodeCreate
  - dialcodeUpdate
  - experimentCreate
  - expirementAccess
  - formCreate
  - formUpdate
  - frameworkAccess
  - frameworkAdmin
  - frameworkCreate
  - frameworkUpdate
  - itemSetAdmin
  - locationAccess
  - locationAdmin
  - locationCreate
  - locationUpdate
  - noteAccess
  - noteAdmin
  - noteCreate
  - noteUpdate
  - objectAccess
  - objectAdmin
  - objectCreate
  - objectUpdate
  - orgAccess
  - orgAdmin
  - orgCreate
  - orgUpdate
  - pageAccess
  - pageCreate
  - pageUpdate
  - pluginAccess
  - ssoAdmin
  - ssoCreate
  - telemetryCreate
  - userAccess
  - userAdmin
  - userCreate
  - userUpdate

kong_consumers:
  - username: api-admin
    groups: "{{ kong_all_consumer_groups }}"
    state: present
  - username: mobile_admin
    groups: "{{ mobile_admin_groups }}"
    print_credentials: true
    state: present
  - username: mobile_app
    groups: "{{ mobile_app_groups }}"
    state: present
  - username: mobile_device
    groups: "{{ mobile_device_groups }}"
    state: present
