---
kong_admin_api_url: "http://{{kong_host}}:8001"

mobile_admin_groups:
  - mobileAdmin

mobile_app_groups:
  - mobileApp

mobile_device_groups:
  - mobileApis

integration_partner_groups:
  - echoUser
  - orgAdmin
  - orgUpdate
  - orgUser
  - userAdmin
  - userUpdate
  - publicUser
  - dataAdmin
  - dataUpdate
  - domainAdmin
  - domainUpdate
  - domainUser
  - dialcodeAdmin
  - dialcodeUpdate
  - dialcodeUser
  - appAdmin
  - appUpdate
  - courseUser
  - contentUser
  - contentAdmin
  - contentUpdate
  - courseAdmin
  - courseUpdate
  - noteAdmin
  - noteUpdate
  - noteUser
  - configUser

implementaion_user_groups:
  - contentAdmin
  - contentUpdate
  - contentUser
  - userAdmin
  - userUpdate
  - publicUser
  - orgAdmin
  - orgUpdate
  - orgUser
  - courseAdmin
  - courseUpdate
  - courseUser
  - dialcodeAdmin
  - dialcodeUpdate
  - dialcodeUser
  - privateContentMgmt

# List all consumer groups in group_vars
kong_all_consumer_groups:
  - appAdmin
  - appUpdate
  - contentAdmin
  - contentUpdate
  - contentUser
  - courseAdmin
  - courseUpdate
  - courseUser
  - echoUser
  - mobileAdmin
  - mobileApp
  - noteAdmin
  - noteUpdate
  - noteUser
  - orgAdmin
  - orgUpdate
  - orgUser
  - publicUser
  - userAdmin
  - userUpdate
  - configUser
  - dataAdmin
  - dataUpdate
  - dialcodeAdmin
  - dialcodeUpdate
  - dialcodeUser
  - domainAdmin
  - domainUpdate
  - domainUser
  - privateContentMgmt

kong_admin_groups:
  - kongConsumer

private_groups:
  - locationAdmin

# List the consumers need to be present as state: present
# List the consumers need to be absent as state: absent
# This role will not update / delete consumers not listed here
kong_consumers:
  - username: api-management-test-user
    groups: "{{ kong_all_consumer_groups }}"
    state: present
  - username: add-any-consumer-to-be-deleted
    state: absent
  - username: player
    groups: "{{ kong_all_consumer_groups }}"
    state: present
    rate_limits: "{{ premium_consumer_rate_limits }}"
  - username: mobile_admin
    groups: "{{ mobile_admin_groups }}"
    print_credentials: true
    state: present
  - username: mobile_app
    groups: "{{ mobile_app_groups }}"
    state: present
  - username: mobile_device
    groups: "{{ mobile_device_groups }}"
    state: present
  - username: kongAdmin
    groups: "{{ kong_admin_groups }}"
    state: present
  - username: mobile_admin_openrap
    groups: ["mobileAdminOpenRAP"]
    save_credentials: true
    state: present
  - username: mobile_app_openrap
    groups: ["mobileAppOpenRAP"]
    state: present
  - username: mobile_device_openrap
    groups: "{{ mobile_device_groups }}"
    state: present
