---
kong_admin_api_url: "http://{{kong_host}}:8001"

mobile_admin_groups:
  - mobileSuperAdmin

mobile_app_groups:
  - mobileAdmin

mobile_device_groups:
  - appAccess
  - certificateAccess
  - contentAccess
  - courseAccess
  - deviceCreate
  - dialcodeAccess
  - locationAccess
  - orgAccess
  - ssoCreate
  - telemetryCreate
  - userAccess
  - userTempAdmin
  - userUpdate

kong_all_consumer_groups:
  - announcementAccess
  - orgCreate
  - appAccess
  - appUpdate
  - badgeAccess
  - certificateAccess
  - channelAccess
  - channelAccess
  - contentAccess
  - contentCreate
  - contentUpdate
  - courseAccess
  - courseCreate
  - courseUpdate
  - deviceCreate
  - dialcodeAccess
  - locationAccess
  - noteAccess
  - noteCreate
  - noteUpdate
  - objectAccess
  - orgAccess
  - pageAccess
  - ssoCreate
  - userAccess
  - certificateCreate
  - certificateUpdate
  - certificateAdmin
  - noteAdmin
  - userCreate
  - userAdmin
  - userUpdate
  - appAdmin
  - contentAdmin
  - channelCreate
  - channelUpdate
  - courseAdmin
  - dialcodeAdmin
  - dialcodeCreate
  - dialcodeUpdate
  - badgeAdmin
  - badgeCreate
  - badgeUpdate
  - pluginAccess
  - userTempAdmin
  - reportsAdmin
  - reportsAccess
  - reportsUpdate
  - reportsCreate
  - privateUserUpdate


kong_consumers:
  - username: api-admin
    groups: "{{ kong_all_consumer_groups }}"
    state: present
  - username: mobile_admin
    groups: "{{ mobile_admin_groups }}"
    print_credentials: true
    state: present
  - username: mobile_app
    groups: "{{ mobile_app_groups }}"
    state: present
  - username: mobile_device
    groups: "{{ mobile_device_groups }}"
    state: present
