---
- name: upload folder to s3
  environment:
    AWS_DEFAULT_REGION: "{{ aws_default_region }}"
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
  shell: "aws s3 cp {{ local_file_or_folder_path }} s3://{{ s3_bucket_name }}/{{ s3_path }} --recursive"
  async: 3600
  poll: 10
