{{- if .Values.oAuthConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name | quote }}
data:
{{- range $path, $config := .Values.oAuthConfig }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}


{{- if .Values.authenticatedEmails }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-auth-emails
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name | quote }}
data:
{{- range $path, $config := .Values.authenticatedEmails }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}

