cassandra_root_dir: '/etc/cassandra'
data_dir: '/var/lib/cassandra/data'
cloud_storage_cassandrabackup_bucketname: "{{cloud_storage_management_bucketname}}"
cloud_storage_cassandrabackup_foldername: 'cassandra-backup'
