groups:
- name: alertrules.docker
  rules:
  - alert: docker_swarm_node_down_FATAL
    expr: swarm_manager_nodes{state="down"} > 0
    for: 5m
    labels:
      severity: FATAL
    annotations:
      description: 'Number nodes down : {% raw %}{{$value}}{% endraw %}'
      summary: 'Docker swarm node down'
