groups:
- name: alertrules.nodes
  rules:
  - alert: high_cpu_usage_on_node_WARNING
    expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{job="vm-node-exporter",mode="idle"}[5m])) * 100) >= {{ node_cpu_usage_percentage_threshold_Warning }} and (avg by (instance) (irate(node_cpu_seconds_total{job="vm-node-exporter",mode="idle"}[5m])) * 100) < {{ node_cpu_usage_percentage_threshold_Critical }}
    for: 1m
    labels:
      severity: WARNING
    annotations:
      description: '{% raw %}{{ $labels.nodename }}{% endraw %}. CPU usage is {% raw %}{{ humanize $value}}{% endraw %}%.'
      summary: 'HIGH CPU USAGE WARNING ON {% raw %}{{ $labels.nodename }}{% endraw %}'
  - alert: high_cpu_usage_on_node_CRITICAL
    expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{job="vm-node-exporter",mode="idle"}[5m])) * 100) >= {{ node_cpu_usage_percentage_threshold_Critical }} and (avg by (instance) (irate(node_cpu_seconds_total{job="vm-node-exporter",mode="idle"}[5m])) * 100) < {{ node_cpu_usage_percentage_threshold_Fatal }}
    for: 1m
    labels:
      severity: CRITICAL
    annotations:
      description: '{% raw %}{{ $labels.nodename }}{% endraw %}: CPU usage is {% raw %}{{ humanize $value}}{% endraw %}%.'
      summary: 'HIGH CPU USAGE WARNING ON {% raw %}{{ $labels.nodename }}{% endraw %}'
  - alert: high_cpu_usage_on_node_FATAL
    expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{job="vm-node-exporter",mode="idle"}[5m])) * 100) >= {{ node_cpu_usage_percentage_threshold_Fatal }}
    for: 1m
    labels:
      severity: FATAL
    annotations:
      description: '{% raw %}{{ $labels.nodename }}{% endraw %}: CPU usage is {% raw %}{{ humanize $value}}{% endraw %}%.'
      summary: 'HIGH CPU USAGE WARNING ON {% raw %}{{ $labels.nodename }}{% endraw %}'
  - alert: high_memory_usage_on_node_WARNING
    expr: sum by(nodename) ((((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * on(instance) group_left(nodename) node_uname_info * 100) >= {{ node_memory_usage_percentage_threshold_Warning }} and (((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * on(instance) group_left(nodename) node_uname_info * 100) < {{ node_memory_usage_percentage_threshold_Critical }} )
    for: 1m
    labels:
      severity: WARNING
    annotations:
      description: '{% raw %}{{ $labels.nodename }}{% endraw %} ({% raw %}{{ $labels.host }}{% endraw %}): MEMORY usage {% raw %}{{ humanize $value}}{% endraw %}.'
      summary: 'WARNING: HIGH MEMORY USAGE ON {% raw %}{{ $labels.nodename }}{% endraw %}'
  - alert: high_memory_usage_on_node_CRITICAL
    expr: sum by(nodename) ((((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * on(instance) group_left(nodename) node_uname_info * 100) >= {{ node_memory_usage_percentage_threshold_Critical }} and (((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * on(instance) group_left(nodename) node_uname_info * 100) < {{ node_memory_usage_percentage_threshold_Fatal }} )
    for: 1m
    labels:
      severity: CRITICAL
    annotations:
      description: '{% raw %}{{ $labels.nodename }}{% endraw %} ({% raw %}{{ $labels.host }}{% endraw %}): MEMORY usage {% raw %}{{ humanize $value}}{% endraw %}.'
      summary: 'WARNING: HIGH MEMORY USAGE ON {% raw %}{{ $labels.nodename }}{% endraw %}'
  - alert: high_memory_usage_on_node_FATAL
    expr: sum by(nodename) (((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * on(instance) group_left(nodename) node_uname_info * 100) >= {{ node_memory_usage_percentage_threshold_Fatal }}
    for: 1m
    labels:
      severity: FATAL
    annotations:
      description: '{% raw %}{{ $labels.nodename }}{% endraw %} ({% raw %}{{ $labels.host }}{% endraw %}): MEMORY usage {% raw %}{{ humanize $value}}{% endraw %}.'
      summary: 'WARNING: HIGH MEMORY USAGE ON {% raw %}{{ $labels.nodename }}{% endraw %}'
  - alert: high_load_on_node_WARNING
    expr: sum by(nodename) (((node_load1 / count without(cpu, mode) (node_cpu_seconds_total{mode="system"}))* on(instance) group_left(nodename) node_uname_info * 100) >= {{ node_load_avg_threshold_Warning }} and ((node_load1 / count without(cpu, mode) (node_cpu_seconds_total{mode="system"}))* on(instance) group_left(nodename) node_uname_info * 100) < {{ node_load_avg_threshold_Critical }} )
    for: 5m
    labels:
      severity: WARNING
    annotations:
      description: '{% raw %}{{ $labels.nodename }}{% endraw %} ({% raw %}{{ $labels.host }}{% endraw %}): Load average {% raw %}{{ $value }}{% endraw %}%.'
      summary: 'WARNING: HIGH LOAD AVERAGE ON {% raw %}{{ $labels.nodename }}{% endraw %}'
  - alert: high_load_on_node_CRITICAL
    expr: sum by(nodename) (((node_load1 / count without(cpu, mode) (node_cpu_seconds_total{mode="system"}))* on(instance) group_left(nodename) node_uname_info * 100) >= {{ node_load_avg_threshold_Warning }} and ((node_load1 / count without(cpu, mode) (node_cpu_seconds_total{mode="system"}))* on(instance) group_left(nodename) node_uname_info * 100) < {{ node_load_avg_threshold_Critical }} )
    for: 5m
    labels:
      severity: CRITICAL
    annotations:
      description: '{% raw %}{{ $labels.nodename }}{% endraw %} ({% raw %}{{ $labels.host }}{% endraw %}): Load average {% raw %}{{ $value }}{% endraw %}%.'
      summary: 'WARNING: HIGH LOAD AVERAGE ON {% raw %}{{ $labels.nodename }}{% endraw %}'
  - alert: high_load_on_node_FATAL
    expr: sum by(nodename) ((node_load1 / count without(cpu, mode) (node_cpu_seconds_total{mode="system"}))* on(instance) group_left(nodename) node_uname_info * 100) > {{ node_load_avg_threshold_Fatal }}
    for: 5m
    labels:
      severity: FATAL
    annotations:
      description: '{% raw %}{{ $labels.nodename }}{% endraw %} ({% raw %}{{ $labels.host }}{% endraw %}): Load average {% raw %}{{ $value }}{% endraw %}%.'
      summary: 'WARNING: HIGH LOAD AVERAGE ON {% raw %}{{ $labels.nodename }}{% endraw %}'

  - alert: Host_Down_FATAL
    expr: up == 0
    for: 1m
    labels:
      severity: FATAL
    annotations:
      description: The node '{% raw %}{{ $labels.host }}{% endraw %}' is down.
      summary: NODE '{% raw %}{{ $labels.host }}{% endraw %}' is down
  - alert: node_running_out_of_disk_space_WARNING
    expr: sum by(nodename) (((node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) * 100 / node_filesystem_size_bytes{mountpoint="/"} * on(instance) group_left(nodename) node_uname_info) >= {{ node_disk_usage_percentage_threshold_Warning }} and ((node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) * 100 / node_filesystem_size_bytes{mountpoint="/"} * on(instance) group_left(nodename) node_uname_info) < {{ node_disk_usage_percentage_threshold_Critical }} )
    for: 1m
    labels:
      severity: WARNING
    annotations:
      description: '{% raw %}{{ $labels.nodename }}{% endraw %} ({% raw %}{{ $labels.host }}{% endraw %}): Disk Usage: {% raw %}{{ $value }}{% endraw %}%.'
      summary: 'LOW DISK SPACE WARING: NODE {% raw %}{{ $labels.nodename }}{% endraw %}'
  - alert: node_running_out_of_disk_space_WARNING
    expr: sum by(nodename) (((node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) * 100 / node_filesystem_size_bytes{mountpoint="/"} * on(instance) group_left(nodename) node_uname_info) >= {{ node_disk_usage_percentage_threshold_Critical }} and ((node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) * 100 / node_filesystem_size_bytes{mountpoint="/"} * on(instance) group_left(nodename) node_uname_info) < {{ node_disk_usage_percentage_threshold_Fatal }} )
    for: 1m
    labels:
      severity: CRITICAL
    annotations:
      description: '{% raw %}{{ $labels.nodename }}{% endraw %} ({% raw %}{{ $labels.host }}{% endraw %}): Disk Usage: {% raw %}{{ $value }}{% endraw %}%.'
      summary: 'LOW DISK SPACE WARING: NODE {% raw %}{{ $labels.nodename }}{% endraw %}'
  - alert: node_running_out_of_disk_space_FATAL
    expr: sum by(nodename) ((node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) * 100 / node_filesystem_size_bytes{mountpoint="/"} * on(instance) group_left(nodename) node_uname_info) >= {{ node_disk_usage_percentage_threshold_Fatal }}
    for: 1m
    labels:
      severity: FATAL
    annotations:
      description: '{% raw %}{{ $labels.nodename }}{% endraw %} ({% raw %}{{ $labels.host }}{% endraw %}): Disk Usage: {% raw %}{{ $value }}{% endraw %}%.'
      summary: 'LOW DISK SPACE WARING: NODE {% raw %}{{ $labels.nodename }}{% endraw %}'
