---
{{- $keys := .Files.Glob "keys/*" }}
{{ if $keys }}
apiVersion: v1
kind: Secret
metadata:
  name: groups-access-keys
type: Opaque
data:
{{ (.Files.Glob "keys/*").AsSecrets | indent 2 }}
{{ end }}
