{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thanos.serviceAccountName" . }}
  labels:
{{ include "thanos.labels" . | nindent 4 }}
{{- end -}}
