- name: Install jq
  apt: name=jq state=present
  become: yes

- name: Copy the templates
  become: yes
  template: src=system_init_commands.j2 dest=/tmp/system_init_commands.sh mode=755

- name: Pausing for container to be fully functional
  pause:
    minutes: 2

- name: Run the system init script
  become: yes
  shell: sh system_init_commands.sh
  args:
    chdir: /tmp/