---
# The version of filebeat to install
filebeat_version: 1.3.1

# `filebeat_config` is templated directly into filebeat.yml for the config.
# You are expected to override this variable, as these configurations are
# only suited for development purposes.
# See https://github.com/elastic/beats/blob/master/filebeat/filebeat.yml for
# an exhaustive list of configurations.
filebeat_config:
  filebeat:
    prospectors:
      - paths:
          - /var/log/messages
          - /var/log/*.log
        input_type: log
  output:
    file:
      path: /tmp/filebeat
      filename: filebeat
  logging:
    to_syslog: true
    level: error

# The contents of this variable will be placed into the `filebeat_ca_path`
# This should either be set to a string containing your CA certificate or
# use a lookup plugin to retrieve it.
#  ex:
#   filebeat_ca_cert: "{{ lookup('file', '/path/to/ca.crt') }}"
filebeat_ca_cert: null
# Path to which the above certificate will be uploaded
filebeat_ca_path: /etc/filebeat/ca.crt

# Similar to the above but for ssl cert and ssl key
filebeat_ssl_cert: null
filebeat_ssl_cert_path: /etc/filebeat/ssl.crt
filebeat_ssl_key: null
filebeat_ssl_key_path: /etc/filebeat/ssl.key

# Repository settings
filebeat_gpg_url: https://packages.elastic.co/GPG-KEY-elasticsearch
## Debian
filebeat_apt_repo_v1: "deb https://packages.elastic.co/beats/apt stable main"
filebeat_apt_repo_v5: "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
filebeat_apt_repo: "{{ filebeat_version|version_compare('5', '<')|ternary(filebeat_apt_repo_v1, filebeat_apt_repo_v5) }}"
## Redhat
filebeat_repo_url_v1: https://packages.elastic.co/beats/yum/el/$basearch
filebeat_repo_url_v5: https://artifacts.elastic.co/packages/5.x/yum
filebeat_repo_url: "{{ filebeat_version|version_compare('5', '<')|ternary(filebeat_repo_url_v1, filebeat_repo_url_v5) }}"
