apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-default
  namespace: {{ .Values.namespace }}
data:
  proxy-default.conf: |
{{ .Values.proxyconfig | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
{{ .Values.nginxconfig | indent 4 }}
