---
daemonset:
  enabled: true
  hostNetworking: false
  filebeatConfig:
    filebeat.yml: |
      filebeat.inputs:
      #==== Flink cluster input config ====#
      - type: container
        paths:
          - /var/log/containers/*-jobmanager-*.log
          - /var/log/containers/*-taskmanager-*.log
          - /var/log/containers/*-secor-*.log
        multiline.type: pattern
        multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
        multiline.negate: true
        multiline.match: after
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

      output.logstash:
        hosts: ["{{ groups['graylog']|join(':5044\", \"')}}:5044"]
        loadbalance: true
  maxUnavailable: 1
  securityContext:
    runAsUser: 0
    privileged: false
  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "1000m"
      memory: "1000Mi"
nameOverride: "filebeat"
fullnameOverride: "filebeat"
graylog:
  hosts:
{% for host in groups['graylog'] %}
    - {{ host }}
{% endfor %}
