replicas: {{ kibana_replicas | default(1) }}
image: "docker.elastic.co/kibana/kibana"
imageTag: "6.8.6"
imagePullPolicy: "IfNotPresent"

resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "4"
    memory: "4Gi"

healthCheckPath: "/dashboard"

kibanaConfig:
   kibana.yml: |
     server.basePath: "/dashboard"
     server.host: "0.0.0.0"
     server.rewriteBasePath: true
     elasticsearch.shardTimeout: 0
     elasticsearch.hosts: ["http://{{groups['log-es'] | join(':9200","http://')}}:9200"] 
     elasticsearch.requestTimeout: 300000
     elasticsearch.preserveHost: true
     elasticsearch.ssl.verificationMode: full

updateStrategy:
  type: "RollingUpdate"

readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 60
  timeoutSeconds: 5
  failureThreshold: 10
  successThreshold: 1

fullnameOverride: "kibana"
