---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: alert-rules
    app: {{ .Values.prometheus_rule_selector_app }}
    release: {{ .Values.prometheus_rule_selector_release }}
  name: {{ .Values.fullnameOverride }}-kafkalag-rules
  namespace: {{ .Values.namespace }}
spec:
  groups:
  - name: alertrules.kafkalag
    rules:
    - alert: secor {{ .Values.kafka_topic_prefix }}.events.deviceprofile.backup group lag
      expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ .Values.kafka_topic_prefix }}.events.deviceprofile.backup"} > {{ .Values.kafka_events_deviceprofile_backup_threshold }}
      for: 5m
      labels:
        severity: critical
      annotations:
        message: {{`"`}}{{ .Values.kafka_topic_prefix }}{{`.events.deviceprofile.backup consumer group lag is {{$value}} for partition: {{ $labels.partition }}"`}}
        summary: secor consumer group lag is more for {{ .Values.kafka_topic_prefix }}.events.deviceprofile.backup
    
    - alert: secor {{ .Values.kafka_topic_prefix }}.telemetry.channel.backup group lag
      expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ .Values.kafka_topic_prefix }}.telemetry.channel.backup"} > {{ .Values.kafka_events_channel_backup_threshold }}
      for: 5m
      labels:
        severity: critical
      annotations:
        message: {{`"`}}{{ .Values.kafka_topic_prefix }}{{`.telemetry.channel.backup consumer group lag is {{$value}} for partition: {{ $labels.partition }}"`}}
        summary: secor consumer group lag is more for {{ .Values.kafka_topic_prefix }}.telemetry.channel.backup
    
    - alert: secor {{ .Values.kafka_topic_prefix }}.telemetry.derived.backup group lag
      expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ .Values.kafka_topic_prefix }}.telemetry.derived.backup"} > {{ .Values.kafka_telemetry_derived_backup_threshold }}
      for: 5m
      labels:
        severity: critical
      annotations:
        message: {{`"`}}{{ .Values.kafka_topic_prefix }}{{`.telemetry.derived.backup consumer group lag is {{$value}} for partition: {{ $labels.partition }}"`}}
        summary: secor consumer group lag is more for {{ .Values.kafka_topic_prefix }}.telemetry.derived.backup
    
    - alert: secor {{ .Values.kafka_topic_prefix }}.telemetry.failed.backup group lag
      expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ .Values.kafka_topic_prefix }}.telemetry.failed.backup"} > {{ .Values.kafka_telemetry_failed_backup_threshold }}
      for: 5m
      labels:
        severity: critical
      annotations:
        message: {{`"`}}{{ .Values.kafka_topic_prefix }}{{`.telemetry.failed.backup consumer group lag is {{$value}} for partition: {{ $labels.partition }}"`}}
        summary: secor consumer group lag is more for {{ .Values.kafka_topic_prefix }}.telemetry.failed.backup
    
    - alert: secor {{ .Values.kafka_topic_prefix }}.telemetry.ingestion.backup consumer group lag
      expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ .Values.kafka_topic_prefix }}.telemetry.ingestion.backup"} > {{ .Values.kafka_telemetry_ingestion_backup_threshold }}
      for: 5m
      labels:
        severity: critical
      annotations:
        message: {{`"`}}{{ .Values.kafka_topic_prefix }}{{`.telemetry.ingestion.backup consumer group lag is {{$value}} for partition: {{ $labels.partition }}"`}}
        summary: secor consumer group lag is more for {{ .Values.kafka_topic_prefix }}.telemetry.ingestion.backup
    
    - alert: secor {{ .Values.kafka_topic_prefix }}.graph.events.backup consumer group lag
      expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ .Values.kafka_topic_prefix }}.graph.events.backup"} > {{ .Values.kafka_graph_events_backup_threshold }}
      for: 5m
      labels:
        severity: critical
      annotations:
        message: {{`"`}}{{ .Values.kafka_topic_prefix }}{{`.graph.events.backup consumer group lag is {{$value}} for partition: {{ $labels.partition }}"`}}
        summary: secor consumer group lag is more for {{ .Values.kafka_topic_prefix }}.graph.events.backup
    
    - alert: secor {{ .Values.kafka_topic_prefix }}.telemetry.raw.backup consumer group lag
      expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ .Values.kafka_topic_prefix }}.telemetry.raw.backup"} > {{ .Values.kafka_telemetry_raw_backup_threshold }}
      for: 5m
      labels:
        severity: critical
      annotations:
        message: {{`"`}}{{ .Values.kafka_topic_prefix }}{{`.telemetry.raw.backup consumer group lag is {{$value}} for partition: {{ $labels.partition }}"`}}
        summary: secor consumer group lag is more for {{ .Values.kafka_topic_prefix }}.telemetry.raw.backup
    
    - alert: secor {{ .Values.kafka_topic_prefix }}.telemetry.unique.backup consumer group lag
      expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ .Values.kafka_topic_prefix }}.telemetry.unique.backup"} > {{ .Values.kafka_telemetry_unique_backup_threshold }}
      for: 5m
      labels:
        severity: critical
      annotations:
        message: {{`"`}}{{ .Values.kafka_topic_prefix }}{{`.telemetry.unique.backup consumer group lag is {{$value}} for partition: {{ $labels.partition }}"`}}
        summary: secor consumer group lag is more for {{ .Values.kafka_topic_prefix }}.telemetry.unique.backup
    
    - alert: secor {{ .Values.kafka_topic_prefix }}.learning.failed.events.backup consumer group lag
      expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ .Values.kafka_topic_prefix }}.learning.failed.events.backup"} > {{ .Values.kafka_learning_failed_events_backup }}
      for: 5m
      labels:
        severity: critical
      annotations:
        message: {{`"`}}{{ .Values.kafka_topic_prefix }}{{`.learning.failed.events.backup consumer group lag is {{$value}} for partition: {{ $labels.partition }}"`}}
        summary: secor consumer group lag is more for {{ .Values.kafka_topic_prefix }}.learning.failed.events.backup
    
    - alert: secor {{ .Values.kafka_topic_prefix }}.telemetry.denorm.backup consumer group lag
      expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ .Values.kafka_topic_prefix }}.telemetry.denorm.backup"} > {{ .Values.kafka_telemetry_denorm_backup }}
      for: 5m
      labels:
        severity: critical
      annotations:
        message: {{`"`}}{{ .Values.kafka_topic_prefix }}{{`.telemetry.denorm.backup consumer group lag is {{$value}} for partition: {{ $labels.partition }}"`}}
        summary: secor consumer group lag is more for {{ .Values.kafka_topic_prefix }}.telemetry.denorm.backup
    
    - alert: secor {{ .Values.kafka_topic_prefix }}.pipeline_metrics consumer group lag
      expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ .Values.kafka_topic_prefix }}.pipeline_metrics"} > {{ .Values.kafka_telemetry_pipeline_metrics_backup }}
      for: 5m
      labels:
        severity: critical
      annotations:
        message: {{`"`}}{{ .Values.kafka_topic_prefix }}{{`.pipeline_metrics consumer group lag is {{$value}} for partition: {{ $labels.partition }}"`}}
        summary: secor consumer group lag is more for {{ .Values.kafka_topic_prefix }}.pipeline_metrics
    
    - alert: secor {{ .Values.kafka_topic_prefix }}.telemetry.extractor.failed consumer group lag
      expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ .Values.kafka_topic_prefix }}.telemetry.extractor.failed"} > {{ .Values.kafka_telemetry_extractor_failed_backup }}
      for: 5m
      labels:
        severity: critical
      annotations:
        message: {{`"`}}{{ .Values.kafka_topic_prefix }}{{`.telemetry.extractor.failed consumer group lag is {{$value}} for partition: {{ $labels.partition }}"`}}
        summary: secor consumer group lag is more for {{ .Values.kafka_topic_prefix }}.telemetry.extractor.failed
    
    - alert: secor {{ .Values.kafka_topic_prefix }}.telemetry.assess consumer group lag
      expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ .Values.kafka_topic_prefix }}.telemetry.assess"} > {{ .Values.kafka_telemetry_assess_backup }}
      for: 5m
      labels:
        severity: critical
      annotations:
        message: {{`"`}}{{ .Values.kafka_topic_prefix }}{{`.telemetry.assess consumer group lag is {{$value}} for partition: {{ $labels.partition }}"`}}
        summary: secor consumer group lag is more for {{ .Values.kafka_topic_prefix }}.telemetry.assess
