---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: alert-rules
    app: {{ .Values.prometheus_rule_selector_app }}
    release: {{ .Values.prometheus_rule_selector_release }}
  name: {{ .Values.fullnameOverride }}-appelasticsearch-rules
  namespace: {{ .Values.namespace }}
spec:
  groups:
  - name: alertrules.appes
    rules:
    - alert: elasticsearch_too_few_nodes_running_CRITICAL
      annotations:
        description: elasticsearch_cluster_health_number_of_nodes{job="elasticsearch-exporter"} < {{ .Values.app_es_server_count }}
        summary: {{`"There are only {{$value}}`}} < {{ .Values.app_es_server_count }} {{` ElasticSearch nodes running"`}}
      expr: elasticsearch_cluster_health_number_of_nodes{job="elasticsearch-exporter"} < {{ .Values.app_es_server_count }}
      for: 1m
      labels:
        severity: critical
    - alert: elasticsearch_too_few_nodes_running_WARNING
      annotations:
        description: elasticsearch_cluster_health_number_of_nodes{job="elasticsearch-exporter"} < {{ .Values.app_es_server_count }}
        summary: {{`"There are only {{$value}}`}} < {{ .Values.app_es_server_count }} {{`ElasticSearch nodes running"`}}
      expr: elasticsearch_cluster_health_number_of_nodes{job="elasticsearch-exporter"} < {{ .Values.app_es_server_count }}
      for: 1m
      labels:
        severity: warning
