---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: alert-rules
    app: {{ .Values.prometheus_rule_selector_app }}
    release: {{ .Values.prometheus_rule_selector_release }}
  name: {{ .Values.fullnameOverride }}-process-rules
  namespace: {{ .Values.namespace }}
spec:
  groups:
  - name: alertrules.process
    rules:
    - alert: tomcat_process_not_running_FATAL
      expr: namedprocess_namegroup_states{groupname="tomcat",state="Sleeping"} < 1
      for: 1m
      labels:
        severity: FATAL
      annotations:
        description: {{`'Number of running processes are: {{$value}}'`}}
        summary: tomcat process is not running
    - alert: search_process_not_running_FATAL
      expr: namedprocess_namegroup_states{groupname="search",state="Sleeping"} < 1
      for: 1m
      labels:
        severity: FATAL
      annotations:
        description: {{`'Number of running processes are: {{$value}}'`}}
        summary: search process is not running
    - alert: neo4j_process_not_running_FATAL
      expr: namedprocess_namegroup_states{groupname="neo4j",state="Sleeping"} < 1
      for: 1m
      labels:
        severity: FATAL
      annotations:
        description: {{`'Number of running processes are: {{$value}}'`}}
        summary: neo4j process is not running
    - alert: kafka_process_not_running_FATAL
      expr: namedprocess_namegroup_states{groupname="kafka",state="Sleeping"} < 1
      for: 1m
      labels:
        severity: FATAL
      annotations:
        description: {{`'Number of running processes are: {{$value}}'`}}
        summary: Kafka process is not running
    - alert: kafka_more_than_one_process_running_CRITICAL
      expr: namedprocess_namegroup_num_procs{groupname="kafka"} > 1
      for: 1m
      labels:
        severity: CRITICAL
      annotations:
        description: {{`'Number of running processes are: {{$value}}'`}}
        summary: More than one process running
    - alert: secor_process_not_running_CRITICAL
      expr: namedprocess_namegroup_states{groupname="secor",state="Sleeping"} != 9
      for: 1m
      labels:
        severity: CRITICAL
      annotations:
        description: {{`'Number of running processes are: {{$value}}'`}}
        summary: Secor process is not running
    - alert: zookeeper_process_not_running_FATAL
      expr: namedprocess_namegroup_states{groupname="zookeeper",state="Sleeping"} < 1
      for: 1m
      labels:
        severity: FATAL
      annotations:
        description: {{`'Number of running processes are: {{$value}}'`}}
        summary: Zookeeper process is not running
    - alert: yarn_process_not_running_FATAL
      expr: namedprocess_namegroup_states{groupname="yarn",state="Sleeping"} < 1
      for: 1m
      labels:
        severity: FATAL
      annotations:
        description: {{`'Number of running processes are: {{$value}}'`}}
        summary: YARN process is not running
    - alert: cassandra_process_not_running_FATAL
      expr: namedprocess_namegroup_states{groupname="cassandra",state="Sleeping"} < 1
      for: 1m
      labels:
        severity: FATAL
      annotations:
        description: {{`'Number of running processes are: {{$value}}'`}}
        summary: Cassandra process is not running
    - alert: elasticsearch_process_not_running_FATAL
      expr: namedprocess_namegroup_states{groupname="elasticsearch",state="Sleeping"} < 1
      for: 1m
      labels:
        severity: FATAL
      annotations:
        description: {{`'Number of running processes are: {{$value}}'`}}
        summary: Elasticsearch process is not running_CRITICAL
    - alert: logstash_process_not_running_CRITICAL
      expr: namedprocess_namegroup_states{groupname="logstash",state="Sleeping"} < 1
      for: 1m
      labels:
        severity: CRITICAL
      annotations:
        description: {{`'Number of running processes are: {{$value}}'`}}
        summary: Logstash process is not running
    - alert: Analytics_api_process_not_running_FATAL
      expr: namedprocess_namegroup_states{groupname="analyticsapi",state="Sleeping"} < 1
      for: 1m
      labels:
        severity: FATAL
      annotations:
        description: {{`'Number of running processes are: {{$value}}'`}}
        summary: Analytics API process is not running
    - alert: druid_zookeeper_process_not_running_FATAL
      expr: namedprocess_namegroup_states{groupname="druidzookeeper",state="Sleeping"} < 1
      for: 1m
      labels:
        severity: FATAL
      annotations:
        description: {{`'Number of running processes are: {{$value}}'`}}
        summary: Druid zookeeper is not running
    - alert: druid_postgres_process_not_running_FATAL
      expr: namedprocess_namegroup_states{groupname="druidpostgres",state="Sleeping"} < 1
      for: 1m
      labels:
        severity: FATAL
      annotations:
        description: {{`'Number of running processes are: {{$value}}'`}}
        summary: Druid postgres is not running
    - alert: druid_overlord_process_not_running_FATAL
      expr: namedprocess_namegroup_states{groupname="overlord",state="Sleeping"} < 1
      for: 1m
      labels:
        severity: FATAL
      annotations:
        description: {{`'Number of running processes are: {{$value}}'`}}
        summary: Druid overlord process is not running
    - alert: druid_coordinator_process_not_running_FATAL
      expr: namedprocess_namegroup_states{groupname="coordinator",state="Sleeping"} < 1
      for: 1m
      labels:
        severity: FATAL
      annotations:
        description: {{`'Number of running processes are: {{$value}}'`}}
        summary: Druid coordinator process is not running
    - alert: druid_historical_process_not_running_FATAL
      expr: namedprocess_namegroup_states{groupname="historical",state="Sleeping"} < 1
      for: 1m
      labels:
        severity: FATAL
      annotations:
        description: {{`'Number of running processes are: {{$value}}'`}}
        summary: Druid historical process is not running
    - alert: druid_broker_process_not_running_FATAL
      expr: namedprocess_namegroup_states{groupname="broker",state="Sleeping"} < 1
      for: 1m
      labels:
        severity: FATAL
      annotations:
        description: {{`'Number of running processes are: {{$value}}'`}}
        summary: Druid broker process is not running
    - alert: druid_middleManager_process_not_running_FATAL
      expr: namedprocess_namegroup_states{groupname="middleManager",state="Sleeping"} < 1
      for: 1m
      labels:
        severity: FATAL
      annotations:
        description: {{`'Number of running processes are: {{$value}}'`}}
        summary: Druid middleManager process is not running
    - alert: redisserver_process_not_running_FATAL
      expr: namedprocess_namegroup_states{groupname="redis-server",state="Sleeping"} < 1
      for: 1m
      labels:
        severity: FATAL
      annotations:
        description: {{`'Number of running processes are: {{$value}}'`}}
        summary: redis-server process is not running
    - alert: influxdb_process_not_running_FATAL
      expr: namedprocess_namegroup_states{groupname="influxd",state="Sleeping"} < 1
      for: 1m
      labels:
        severity: FATAL
      annotations:
        description: {{`'Number of running processes are: {{$value}}'`}}
        summary: influxdb process is not running
    - alert: druid_health_status_FATAL
      expr: http_druid_health_check_status < 99
      for: 1m
      labels:
        severity: FATAL
      annotations:
        {{`description: 'Druid health for Datasource is < {{ $value }}'`}}
        summary: {{`'Druid health for Datasource is < {{ $value }}'`}}
  
