- name: copy the template lock_config
  template: src=lock_config.j2 dest=/home/deployer/lock_config.js mode=0777 

- name: run the template lock_config
  become: yes
  shell: mongo < /home/deployer/lock_config.js

