domain: ""                            # Domain name  ed.example.com
cloud_public_storage_accountname: ""  # name of the azure storage account
cloud_public_storage_secret: ""      # Access key of the azure storage account. You can get the value by login to azure portal -> Select the storage account -> Select Access Keys from the left side panel -> Click show button for Key -> Copy the key

# core_vault_proxy_site_key: |+
#   -----BEGIN PRIVATE KEY-----
#   -----END PRIVATE KEY----
# core_vault_proxy_site_crt: |+
#   -----BEGIN CERTIFICATE-----
#     -----END CERTIFICATE-----  
# SSL Private Key ie private.key
core_vault_proxy_site_key: |+ 

# SSL Public Key(Bundle+CA)
core_vault_proxy_site_crt: |+

# openssl genrsa -out key.pem; cat key.pem;
# openssl rsa -in key.pem -pubout -out pubkey.pem;

CERTIFICATE_PRIVATE_KEY: |          # update te content from key.pem which is generated in line 19(openssl command)
#   -----BEGIN PRIVATE KEY-----
#   -----END PRIVATE KEY----- 

CERTIFICATE_PUBLIC_KEY: |           # update te content from pubkey.pem which is generated in line 20 (openssl command)
#   -----BEGIN PUBLIC KEY-----
#   -----END PUBLIC KEY-----
core_vault_sunbird_google_captcha_site_key_portal: ""      # Google reCaptcha site Key       
google_captcha_private_key: ""         # Google reCaptcha private Key
sunbird_google_oauth_clientId : ""     # Google OAuth Client ID 
sunbird_google_oauth_clientSecret : "" #Google OAuth Client Secret 
nginx_private_ingress_ip: ""        # Pick an free IP from Pod CIDR Range. if PodCIDRRange  is 192.168.0.0/16 then add 192.168.0.200 as value

####DONT CHANGE IT #####
sunbird_pg_host: postgresql.dev.svc.cluster.local
sunbird_redis_host: redis-master.dev.svc.cluster.local
sunbird_user_org_api_base_url: http://learner.dev.svc.cluster.local:9000
sunbird_user_service_api_base_url: http://learner.dev.svc.cluster.local:9000
sunbird_cassandra_host: cassandra.dev.svc.cluster.local
sunbird_cert_service_base_url: http://cert-service.dev.svc.cluster.local:9000
sunbird_es_host: http://elasticsearch.dev.svc.cluster.local
sunbird_group_service_api_base_url: http://groups.dev.svc.cluster.local:9000
redis__host: redis-master.dev.svc.cluster.local
kong_pg_host: postgresql.dev.svc.cluster.local
kong_admin_listen: 0.0.0.0:8001
learning_service_base_url: http://learning.dev.svc.cluster.local:8080/learning-service
sunbird_analytics_api_base_url: http://analytics-service.dev.svc.cluster.local:9000
sunbird_cs_base_url: http://knowledge-mw-service.dev.svc.cluster.local:5000"
sunbird_sso_username: "admin"
sunbird_sso_password: "sunbird"
sunbird_pg_user: "postgres"  
sunbird_pg_password: "postgres"
connectionInfo_username: "admin"   
connectionInfo_password: "password"
sunbird_sso_realm: sunbird
cloud_service_provider: "azure"       # Can be one of - azure, aws, gcloud
cloud_public_storage_container: sunbird-content-dev     # STORAGE CONTAINER NAME eg : storageacc
checkpoint_store_type: "azure"  # DEFAULT AZURE
CACHE_CONTEXT_URLS: https://sunbirdstagingpublic.blob.core.windows.net/sunbird-content-staging/schema/v1_context.json,https://sunbirdstagingpublic.blob.core.windows.net/sunbird-content-staging/schema/sunbird_context.json,https://sunbirdstagingpublic.blob.core.windows.net/sunbird-content-staging/schema/credential_template.json
sunbird_encryption_key: "aead61390a587dbf7d10"
cloud_storage_flink_bucketname: "flink-state-backend" 

## OPTIONAL####
sunbird_msg_91_auth: ""             
sunbird_msg_sender: "SUNBIRD"  
sunbird_mail_server_from_email: ""  # EMAIL Address
sunbird_mail_server_host: ""        # SMTP Host smtp.sendgrid.com  
sunbird_mail_server_password: ""    # SMTP PASSWORD 
sunbird_mail_server_port: ""        # DEFAULT 587
sunbird_mail_server_username: ""    # SMTP EMAIL ID   
cloud_storage_endpoint: ""          

############## VALUES TO BE FILLED AFTER FIRST STEP OF INSTALL ###################
# Take values from Keycloak
# Go to http://localhost:8080/auth/admin/master/console/#/realms/sunbird/clients -> lms -> service account roles -> Click on client roles drop down -> Select realm-management -> Select manage-users in Available Roles -> Click on Add selected
sunbird_sso_publickey: ""                             # Go to http://localhost:8080/auth/admin/master/console/#/realms/sunbird/keys
sunbird_sso_client_secret: ""                         # Go to http://localhost:8080/auth/admin/master/console/#/realms/sunbird/clients -> lms -> credentials --> copy the secret value              
sunbird_keycloak_user_federation_provider_id: ""      # Go to  http://localhost:8080/auth/admin/master/console/#/realms/sunbird/user-federation --> click on cassandra-storage-provider -->copy the provider key

global:
  keycloak_sunbird_realm_kid: ""              # Go to http://localhost:8080/auth/admin/master/console/#/realms/sunbird/keys -->copy RSA KID
  keycloak_sunbird_realm_public_key: ""       # Go to http://localhost:8080/auth/admin/master/console/#/realms/sunbird/keys  
  # Below  values are testing purpose
  user_access_private_keys:  
    accessv1_key1: |
      -----BEGIN PRIVATE KEY-----
      MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC5GDQK2PSrnojv
      g3vYBuJuHslvgv+IdqtnFhMEwQrfJJd4PNkxATR69/OO2OO4xd8tC+bQYkPcImO0
      Y3ynvsVwbJ2che2dS6RvsZh5Es7dpcf7UVp9AQb4QPTvGDYagrekf3cpdy3CoeZm
      lb1jOmJKP6YS4PIqmeO4dfsz0p2rNraeg42Dpgt6wcievSvyXIf6QqDwCpp/HnK4
      Kso2yL9XSUE87Khhb6itbAos9TnRpraVZYho2WuDTXQYfYZHEr8EzX1mS8dQhJTr
      N6Nl7PVteVfxFqQR41a1WB/w5Lx3iYawhmuI1eSuAmZT3PoeRTXFalJlyNJb74je
      DgOYCYiTAgMBAAECggEAM4DkmlAcZNTMTblMcKQZxYKTko/lAtfigeDGkgAVQlow
      O6jS1qv7KmxsPUdktjl5DFPPehSdxVdcXwl/2j1fOxU+Fhu+LpKpwtqsDqSJI2vJ
      5ciRYU8z3UhV32HhTCcran59bfBXr1zVe54XANFyIC7tyzsEp44Cq4VIzPbCIK2z
      oSYul4ydJmuJ6THsDNdWSWGyE/1iNGD94JnlIuQZ+0r/GXRf9BDLnNPKVfj2lcO5
      OuNTZE5jkrgSC+TXoHV7m32V/4XQRpJZ2aAr2LrBCW4iy+3/IbgFmKr6HfQIoHWY
      K9Vgk8wdcBnfcTdoCHVE42fzHqIom/R8STRFVNHswQKBgQDdy3AcFhW9TFRw0Sa+
      JOG2qXgKLQWyKxaH5jfdGsQw0nUT08fgTlDCxcC64ByIzmc02l4kB23a6XzViR4v
      /K3519A5iKfC1alfMFcDokDjPRkdiZ5hHaPfWBrLp+KL0GtoAogR6qyE9i47XFqQ
      VC/zAPoRoBjwFFO6RGkTkuwcCQKBgQDVo9N9I7vtG2G2+LcXoCxUFcZw8ogpYmrT
      m1DKAMQxid5rc/0P1OSdudtjYMpdXPKXeyztHhFxBwlvZG5kiPz/yRO0jHJTQbZP
      yP/hZOf2Dcwmf0RyIFbynBD8Vkla/ChjDbZM6Sv+6GkXU4DvjAQdh1Um5923EZML
      OKkraggeuwKBgQDVXivI6ToatL6bFaomzAZUGi4/49YR87+mF0RwsZpBuYUmANvN
      Hqo05dcmMAljVuUUhGqCUJ9PNMWCC3n+AiBANWy8nIl/NtrMlw1ukn3H3fQ2ZTj3
      BnOqnfCRMT4Q8P0SvzS1v8Qd2VLailsZc9P4+1yW7iRvea6eh8dqLDJ2OQKBgCbO
      Gxwf4YKv9o/FnXwtG+AqFGFvrEvYFI9bJtGKUhitcjkSWGUHxn7fw3nJmvhaabYa
      KY7oZ0KghJY3J9YbC9lqLKoe2KVGylazq8bFDV0kJHDZrRUNyr1Gm8853RkptCxJ
      0VMnB1bF4FDcWg8o35Z9fnoSo7Mc/hiLsi6wk8kBAoGAVaojV+zrC07VDcLKNtsh
      R+87iJCNldFV1X2rfPYFMLDWyLubd0g1v8ulYlk3KRv2MNYftaNHT4PXNSZuhfJy
      mg13rZDoFKFB5DRpfv6ybZIaGxrZ9R+2lV2pFCgFuTExtAufN/JeXM6hNzdAzRgK
      dhMts6drDP0QTO0yK99dPa4=
      -----END PRIVATE KEY-----
    accessv1_key2: |
      -----BEGIN PRIVATE KEY-----
      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDoxlV1cR2IXQtj
      3kEpgnTySHWncmdtBOeNKVBQetZ14CSqVadLHsK+sZgeRm0zY6GURn6IxWaxUbhG
      sHhc6WKKOhKFOOgjv38E7eDq6llnH2hOA8Lypu63Ijdbc2ifYCpuyfwRT9vEpbFo
      vE1SqSZmplkOh1+zFjzf2TypZcdLLRABkGd/0ZelOG9qx7bM2th8nOcH/uVsFO5R
      YELvRkEUUegNvIUq6MtVRH4A1hE3a5EYtPQD9KV8VcyMVET883MgL5tSI8Mhu2nL
      mNY6Q7Stnp6VemuCCe5hd9SRnfr0ytV0K9JaA4zAS4isEHwcP97oyhNs6IhL64iw
      7FQwshxnAgMBAAECggEBAIq/bcELI6dcjqWAnSa49CxWtIqSzsNU4RBrR8ww7BRm
      /nPpikZkl4BDK4EgSYcQJAfV3SZ5Q7T+GPFJzvTSyEHMS63NNdHZG0U85YwhFBk7
      x1h5NYKdrjzK0GRabkpRb/mJvA41o7GbchwT4aMb4B/fl8XpO0nsP2zOeDIg0KIl
      nxiZToaZocwJh4IkfYMnOhSp617ZBbLb25cdRAIEQaGLRuoqibfmB+cBMmQUGFNB
      O9/efJLVTAWk5NvmOWMZ2Wgs6cjIWZPVDXXbAzz+XWQqi4+6He3NGaJ+vq2NdXGc
      hw3V8BwJGsh9/3usoc2lS9QXDkX771N7WFzmOw3u/EECgYEA9P+cUJNTsvuy0RJC
      ZhewTidY15WkwxBPoUqmTOnfFEMw/DO4jC6JWXFb45lANuooFiQwb8svM6Y+o6hP
      NkPaxt426fEU0F4beBid1vUrOk/4a6SRFUdwPzDaDUwc2+Wwo0QxNlXG6mKPtC12
      dnOtF139edQ24uNdi6oegR2qsu0CgYEA8zo0bEZ0gZdBcMNJtVEoQHAv4DSDGieL
      HghLKaqLsVBWFDysV4w7y8Tqy8GPRUG4MCKIa1zhjY0AY92afdvwYStVhyNj+BWT
      qvTTTYsFvvnUO0MUV5ewwX1QcPLns27SGteN/p5PrEOsJ5R9NDLUJWCGOk3QYscd
      dI7cWNcXfiMCgYBpDt8x8is3GhWw75qHeusAaIEBWUsg1nK/IGq1mqgtYS61R1yA
      yEffkeusaoANzFVKQVR/6+oexNAhj7//7hL3qjx0Dww02dX/ptawYcuaosZNKnGI
      ZWztu/4VK6lIZnNbX5eWzCuTQJaM1d3xp2L3HTffsS+kFYl8pYOVLGqRdQKBgEH0
      F4EAvdjiFfmoytTi0+JdSW4nbyFpdZzILPF4cHa9TQohxa3btd80X2Ku8tWZ04Mh
      6hIK1pKWmHN8BMd6Gz2ODZweaZ4845To3F9bgkxd3EHRl7OEy4Y8H9Lw2wlZ1Jk4
      uCVB8mLI2ubEqgq8ebBE80DeFtKiIYeYsYFZmeI3AoGBAKUWA7KqJ+Gw5QIbJ680
      bZqKZliuCzI4HkXeNNFYv9+8ec+P6prbfP6WlAsjLsPVJj5gV1A/55syhvPzfSXw
      GAcMqQqWTYIyoLJ+idyitJVuFmXi/eAaNDIh001Itz8R6uPWIR/KqIJUagc8ZzcS
      S/euzu2m6qX8poTQAo+NoUp2
      -----END PRIVATE KEY-----

  user_access_public_keys:
    accessv1_key1: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuRg0Ctj0q56I74N72Abi
      bh7Jb4L/iHarZxYTBMEK3ySXeDzZMQE0evfzjtjjuMXfLQvm0GJD3CJjtGN8p77F
      cGydnIXtnUukb7GYeRLO3aXH+1FafQEG+ED07xg2GoK3pH93KXctwqHmZpW9Yzpi
      Sj+mEuDyKpnjuHX7M9Kdqza2noONg6YLesHInr0r8lyH+kKg8Aqafx5yuCrKNsi/
      V0lBPOyoYW+orWwKLPU50aa2lWWIaNlrg010GH2GRxK/BM19ZkvHUISU6zejZez1
      bXlX8RakEeNWtVgf8OS8d4mGsIZriNXkrgJmU9z6HkU1xWpSZcjSW++I3g4DmAmI
      kwIDAQAB
      -----END PUBLIC KEY-----
    accessv1_key2: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6MZVdXEdiF0LY95BKYJ0
      8kh1p3JnbQTnjSlQUHrWdeAkqlWnSx7CvrGYHkZtM2OhlEZ+iMVmsVG4RrB4XOli
      ijoShTjoI79/BO3g6upZZx9oTgPC8qbutyI3W3Non2Aqbsn8EU/bxKWxaLxNUqkm
      ZqZZDodfsxY839k8qWXHSy0QAZBnf9GXpThvase2zNrYfJznB/7lbBTuUWBC70ZB
      FFHoDbyFKujLVUR+ANYRN2uRGLT0A/SlfFXMjFRE/PNzIC+bUiPDIbtpy5jWOkO0
      rZ6elXprggnuYXfUkZ369MrVdCvSWgOMwEuIrBB8HD/e6MoTbOiIS+uIsOxUMLIc
      ZwIDAQAB
      -----END PUBLIC KEY-----
