kong_private_key_path: "keys"
kong_private_key_sign_start: 0
kong_private_key_sign_end: 1
kong_private_key_sign_incr: 1

## The below needs to be defined in private repo if you want to use this role ##
#kong_mobile_v2_consumer: "device"
#kong_desktop_v2_consumer: "desktop"
#kong_portalv2_consumer: "portal"

kong_mount_roles_values:
- key_to_register: device
  values_to_pass:
    basepath: "{{ kong_private_key_path }}"
    keyprefix: "{{ adminutil__device_keyprefix }}"
    keystart: "{{ adminutil__device_keystart }}"
    keycount: "{{ adminutil__device_keycount }}"
    kong_consumer: "{{ kong_mobile_v2_consumer }}"
  role_to_run:
    - decrypt.yml
    - generate-keys.yml
    - onboard-keys.yml
- key_to_register: desktop
  values_to_pass:
    basepath: "{{ kong_private_key_path }}"
    keyprefix: "{{ adminutil__desktop_keyprefix }}"
    keystart: "{{ adminutil__desktop_keystart }}"
    keycount: "{{ adminutil__desktop_keycount }}"
    kong_consumer: "{{ kong_desktop_v2_consumer }}"
  role_to_run:
    - decrypt.yml
    - generate-keys.yml
    - onboard-keys.yml
- key_to_register: portal
  values_to_pass:
    basepath: "{{ kong_private_key_path }}"
    keyprefix: "{{ adminutil__portal_keyprefix }}"
    keystart: "{{ adminutil__portal_keystart }}"
    keycount: "{{ adminutil__portal_keycount }}"
    kong_consumer: "{{ kong_portal_v2_consumer }}"
  role_to_run:
    - decrypt.yml
    - generate-keys.yml
    - onboard-keys.yml
