kafka_topic_prefix: "{{ env_name }}"
app_es_server_count: "{{ groups['es'] | length }}"
log_es_server_count: "{{ groups['log-es-2'] | length }}"
cassandra_server_count: "{{ groups['cassandra'] | length }}"
log_es_threshold: 30
secor_job_count: "{{ secor_job_count | d(18) }}"
processingsecor_job_count: "{{ processingsecor_job_count | d(18) }}"

kafka_telemetry_assess_backup_warning: "{{ kafka_telemetry_assess_backup_warning }}"
kafka_telemetry_assess_raw_backup_threshold_warning: "{{ kafka_telemetry_assess_raw_backup_threshold_warning }}"
content_consumption_events_backup_threshold_warning: "{{ content_consumption_events_backup_threshold_warning }}"
kafka_telemetry_denorm_backup_threshold_warning: "{{ kafka_telemetry_denorm_backup_threshold_warning }}"
kafka_telemetry_derived_backup_threshold_warning: "{{ kafka_telemetry_derived_backup_threshold_warning }}"
kafka_events_deviceprofile_backup_threshold_warning: "{{ kafka_events_deviceprofile_backup_threshold_warning }}"
kafka_telemetry_extractor_duplicate_backup_threshold_warning: "{{ kafka_telemetry_extractor_duplicate_backup_threshold_warning }}"
kafka_telemetry_extractor_failed_backup_threshold_warning: "{{ kafka_telemetry_extractor_failed_backup_threshold_warning }}"
kafka_telemetry_failed_backup_threshold_warning: "{{ kafka_telemetry_failed_backup_threshold_warning }}"
kafka_telemetry_ingestion_backup_threshold_warning: "{{ kafka_telemetry_ingestion_backup_threshold_warning }}"
kafka_graph_events_backup_threshold_warning: "{{ kafka_graph_events_backup_threshold_warning }}"
kafka_learning_failed_events_backup_warning: "{{ kafka_learning_failed_events_backup_warning }}"
kafka_telemetry_raw_backup_threshold_warning: "{{ kafka_telemetry_raw_backup_threshold_warning }}"
kafka_telemetry_duplicate_backup_threshold_warning: "{{ kafka_telemetry_duplicate_backup_threshold_warning }}"
kafka_telemetry_ingestion_backup_threshold_warning: "{{ kafka_telemetry_ingestion_backup_threshold_warning }}"
kafka_telemetry_unique_backup_threshold_warning: "{{ kafka_telemetry_unique_backup_threshold_warning }}"
summary_backup_threshold_warning: "{{ summary_backup_threshold_warning }}"
summary_channel_backup_threshold_warning: "{{ summary_channel_backup_threshold_warning }}"

kafka_telemetry_assess_backup_critical: "{{ kafka_telemetry_assess_backup_critical }}"
kafka_telemetry_assess_raw_backup_threshold_critical: "{{ kafka_telemetry_assess_raw_backup_threshold_critical }}"
content_consumption_events_backup_threshold_critical: "{{ content_consumption_events_backup_threshold_critical }}"
kafka_telemetry_denorm_backup_threshold_critical: "{{ kafka_telemetry_denorm_backup_threshold_critical }}"
kafka_telemetry_derived_backup_threshold_critical: "{{ kafka_telemetry_derived_backup_threshold_critical }}"
kafka_events_deviceprofile_backup_threshold_critical: "{{ kafka_events_deviceprofile_backup_threshold_critical }}"
kafka_telemetry_extractor_duplicate_backup_threshold_critical: "{{ kafka_telemetry_extractor_duplicate_backup_threshold_critical }}"
kafka_telemetry_extractor_failed_backup_threshold_critical: "{{ kafka_telemetry_extractor_failed_backup_threshold_critical }}"
kafka_telemetry_failed_backup_threshold_critical: "{{ kafka_telemetry_failed_backup_threshold_critical }}"
kafka_telemetry_ingestion_backup_threshold_critical: "{{ kafka_telemetry_ingestion_backup_threshold_critical }}"
kafka_graph_events_backup_threshold_critical: "{{ kafka_graph_events_backup_threshold_critical }}"
kafka_learning_failed_events_backup_critical: "{{ kafka_learning_failed_events_backup_critical }}"
kafka_telemetry_raw_backup_threshold_critical: "{{ kafka_telemetry_raw_backup_threshold_critical }}"
kafka_telemetry_duplicate_backup_threshold_critical: "{{ kafka_telemetry_duplicate_backup_threshold_critical }}"
kafka_telemetry_ingestion_backup_threshold_critical: "{{ kafka_telemetry_ingestion_backup_threshold_critical }}"
kafka_telemetry_unique_backup_threshold_critical: "{{ kafka_telemetry_unique_backup_threshold_critical }}"
summary_backup_threshold_critical: "{{ summary_backup_threshold_critical }}"
summary_channel_backup_threshold_critical: "{{ summary_channel_backup_threshold_critical }}"


raw_druid_datasource:
  - content-model-snapshot
  - offline-desktop-events
  - summary-events
  - telemetry-events-syncts
  - telemetry-feedback-events
  - audit-rollup-syncts
  - sl_observation_status
  - sl_observations_production
  - telemetry-feedback-events

druid_raw_ingestion_threshold: "{{ druid_raw_ingestion_lag_threshold | default(200000) }}"
druid_rollup_ingestion_threshold: "{{ druid_rollup_ingestion_lag_threshold  | default(200000)}}"
rollup_druid_datasource:
  {{ rollup_druid_datasource | to_yaml | indent( width=2) }}

secor_process_names:
  - channel-telemetry-backup
  - derived-telemetry-backup
  - derived-denorm-events-backup
  - channel-summary-backup
  - assess-events-backup
  - assess-raw-events-backup
  - device-profile-backup
  - learning-events-backup
  - learning-failed-backup
  - content-consumption-events-backup
  - failed-telemetry-backup
  - extractor-duplicate-backup
  - extractor-failed-backup
  - unique-telemetry-backup
  - denorm-events-backup
  - raw-telemetry-backup
  - ingestion-telemetry-backup
  - ingestion-cluster-telemetry-backup
  - telemetry-ingest-backup

redis_process_names:
  {{ redis_process_names | to_yaml | indent( width=2) }}

service_health_checks:
  {{ service_health_checks | to_yaml | indent( width=2) }}
