kafka_topic_prefix: "{{ env_name }}"
app_es_server_count: "{{ groups['es'] | length }}"
log_es_server_count: "{{ groups['log-es-2'] | length }}"
cassandra_server_count: "{{ groups['cassandra'] | length }}"
log_es_threshold: 30
secor_job_count: "{{ secor_job_count | d(18) }}"
processingsecor_job_count: "{{ processingsecor_job_count | d(18) }}"

kafka_telemetry_assess_backup_warning: "{{ kafka_telemetry_assess_backup_warning }}"
kafka_telemetry_assess_raw_backup_threshold_warning: "{{ kafka_telemetry_assess_raw_backup_threshold_warning }}"
content_consumption_events_backup_threshold_warning: "{{ content_consumption_events_backup_threshold_warning }}"
kafka_telemetry_denorm_backup_threshold_warning: "{{ kafka_telemetry_denorm_backup_threshold_warning }}"
kafka_telemetry_derived_backup_threshold_warning: "{{ kafka_telemetry_derived_backup_threshold_warning }}"
kafka_events_deviceprofile_backup_threshold_warning: "{{ kafka_events_deviceprofile_backup_threshold_warning }}"
kafka_telemetry_extractor_duplicate_backup_threshold_warning: "{{ kafka_telemetry_extractor_duplicate_backup_threshold_warning }}"
kafka_telemetry_extractor_failed_backup_threshold_warning: "{{ kafka_telemetry_extractor_failed_backup_threshold_warning }}"
kafka_telemetry_failed_backup_threshold_warning: "{{ kafka_telemetry_failed_backup_threshold_warning }}"
kafka_telemetry_ingestion_backup_threshold_warning: "{{ kafka_telemetry_ingestion_backup_threshold_warning }}"
kafka_graph_events_backup_threshold_warning: "{{ kafka_graph_events_backup_threshold_warning }}"
kafka_learning_failed_events_backup_warning: "{{ kafka_learning_failed_events_backup_warning }}"
kafka_telemetry_raw_backup_threshold_warning: "{{ kafka_telemetry_raw_backup_threshold_warning }}"
kafka_telemetry_duplicate_backup_threshold_warning: "{{ kafka_telemetry_duplicate_backup_threshold_warning }}"
kafka_telemetry_ingestion_backup_threshold_warning: "{{ kafka_telemetry_ingestion_backup_threshold_warning }}"
kafka_telemetry_unique_backup_threshold_warning: "{{ kafka_telemetry_unique_backup_threshold_warning }}"
summary_backup_threshold_warning: "{{ summary_backup_threshold_warning }}"
summary_channel_backup_threshold_warning: "{{ summary_channel_backup_threshold_warning }}"

kafka_telemetry_assess_backup_critical: "{{ kafka_telemetry_assess_backup_critical }}"
kafka_telemetry_assess_raw_backup_threshold_critical: "{{ kafka_telemetry_assess_raw_backup_threshold_critical }}"
content_consumption_events_backup_threshold_critical: "{{ content_consumption_events_backup_threshold_critical }}"
kafka_telemetry_denorm_backup_threshold_critical: "{{ kafka_telemetry_denorm_backup_threshold_critical }}"
kafka_telemetry_derived_backup_threshold_critical: "{{ kafka_telemetry_derived_backup_threshold_critical }}"
kafka_events_deviceprofile_backup_threshold_critical: "{{ kafka_events_deviceprofile_backup_threshold_critical }}"
kafka_telemetry_extractor_duplicate_backup_threshold_critical: "{{ kafka_telemetry_extractor_duplicate_backup_threshold_critical }}"
kafka_telemetry_extractor_failed_backup_threshold_critical: "{{ kafka_telemetry_extractor_failed_backup_threshold_critical }}"
kafka_telemetry_failed_backup_threshold_critical: "{{ kafka_telemetry_failed_backup_threshold_critical }}"
kafka_telemetry_ingestion_backup_threshold_critical: "{{ kafka_telemetry_ingestion_backup_threshold_critical }}"
kafka_graph_events_backup_threshold_critical: "{{ kafka_graph_events_backup_threshold_critical }}"
kafka_learning_failed_events_backup_critical: "{{ kafka_learning_failed_events_backup_critical }}"
kafka_telemetry_raw_backup_threshold_critical: "{{ kafka_telemetry_raw_backup_threshold_critical }}"
kafka_telemetry_duplicate_backup_threshold_critical: "{{ kafka_telemetry_duplicate_backup_threshold_critical }}"
kafka_telemetry_ingestion_backup_threshold_critical: "{{ kafka_telemetry_ingestion_backup_threshold_critical }}"
kafka_telemetry_unique_backup_threshold_critical: "{{ kafka_telemetry_unique_backup_threshold_critical }}"
summary_backup_threshold_critical: "{{ summary_backup_threshold_critical }}"
summary_channel_backup_threshold_critical: "{{ summary_channel_backup_threshold_critical }}"


raw_druid_datasource:
  - content-model-snapshot
  - offline-desktop-events
  - summary-events
  - telemetry-events-syncts
  - telemetry-feedback-events
  - audit-rollup-syncts
  - sl_observation_status
  - sl_observations_production
  - telemetry-feedback-events

rollup_druid_datasource:
  - audit-rollup-syncts
  - error-rollup-syncts
  - summary-distinct-counts
  - summary-monthly-rollup-syncts
  - summary-rollup-syncts
  - telemetry-rollup-syncts

druid_raw_ingestion_threshold: 200000
druid_rollup_ingestion_threshold: 200000

