es:
  uri: "http://{{ groups['log-es-1'][0] }}:9200"
serviceMonitor:
  enabled: true
  #  namespace: monitoring
  labels: # labels with which the prometheus choose the serviceMonitor
    app: monitoring
    release: prometheus-operator
  interval: 60s
  scrapeTimeout: 30s
  scheme: http
