# Oauth client configuration specifics
config:
  # OAuth client ID
  clientID: "{{ grafana_google_oauth_client_id }}"
  # OAuth client secret
  clientSecret: "{{ grafana_google_oauth_client_secret }}"
  # Create a new secret with the following command
  # openssl rand -base64 32 | head -c 32 | base64
  cookieSecret: "{{ cookie_secret }}"
  # Default configuration, to be overridden
  configFile: |-
    redirect_url = "https://{{ domain_name }}/oauth3/callback"
extraArgs:
  proxy-prefix: /oauth3
authenticatedEmailsFile:
  enabled: true
  # New line seperated email ids for ansible variable.
  # eg:
  # grafana_login_whitelisted_emails: |-
  #   user1@gmail.com
  #   user2@mycompany.com
  restricted_access: |-
{{ grafana_login_whitelisted_emails | indent( width=4, first=True)  }}
