kafkaExporter:
  zookeeper:
    servers: ["{{ groups['flink-processing-cluster-zookeepers'] | difference(["localhost"]) | map('regex_replace', '^(.*)$', '\\1:2181') | list | join("\", \"") }}"]
  kafka:
    servers: ["{{ groups['flink-processing-cluster-kafka'] | difference(["localhost"]) | map('regex_replace', '^(.*)$', '\\1:9092') | list | join("\", \"") }}"]
  additionalFlags:
    - --use.consumelag.zookeeper

prometheus:
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: "120s"
    scrapeTimeout: "90s"
    additionalLabels:
      app: prometheus-operator
      release: prometheus-operator
