#jinja2:lstrip_blocks: True
{#
# This name is used to define the 
# additionalScrapeConfigs name
# {{ fullnameOverride }}-prometheus-scrape-confg
# If you change this, make sure to update the value in 
# additionalScrapeConfigs/defautls/main.yaml
#}
fullnameOverride: sunbird-monitoring

# Enabling external prometheus scrape config 
prometheus:
  prometheusSpec:
    additionalScrapeConfigsExternal: {{ additional_scrape_configs_enabled | d(true) }}
    retention: "{{ prometheus_retention_time | d('90d') }}"
    externalLabels:
      cluster: "{{ kubernetes_cluster_name | default('kubernetes-1')}}"
      env: "{{ env }}"
{% if prometheus_storage_spec is defined and prometheus_storage_spec %}
    storageSpec: {{ prometheus_storage_spec|to_json }}
{% endif %}
{% if prometheus_service is defined and prometheus_service %}
  service: {{ (prometheus_service | to_json) }}
{% endif %}

# Enabling monitoring kubelet monitoring over http
kubelet:
  serviceMonitor:
    https: false

alertmanager:
  config:
    global:
      smtp_from: "{{ monitor_alerts_mail_from_email }}"
      smtp_smarthost: "{{ monitor_alerts_mail_server_host }}:{{ monitor_alerts_mail_server_port}}"
      smtp_auth_username: "{{ monitor_alerts_mail_server_username }}"
      smtp_auth_password: "{{ monitor_alerts_mail_server_password }}"

    route:
      receiver: '{{env}}_devops_team'
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      routes:
      - receiver: slack
        continue: true
      - match:
          module: dp
        receiver: dp-slack
      {% for item in alert_teams %}
      # Comment to ensure proper indentation while templating
      - match_re:
          {{ item.group }}: "{{ item.services | join('|') }}"
        receiver: "{{ item.team }}"
        # Comment to ensure proper indentation while templating
        {% if item.severity_mailing_filter is defined and item.severity_mailing_filter|length %}
        routes:
        {% for filter in item.severity_mailing_filter %}
        # Comment to ensure proper indentation while templating
        - match:
            severity: "{{ filter.severity }}"
          receiver: "{{ item.team }}_{{ filter.severity }}"
        {% endfor %}
        {% endif %}
      {% endfor %}
      # Comment to ensure proper indentation while templating
      - match:
          owner:
        receiver: {{env}}_devops_team

    receivers:
      - name: 'slack'
        slack_configs:
          - send_resolved: true
            api_url: "{{ monitor_alerts_slack_url }}"
            username: 'Monitor - Alerter'
            channel: "{{ monitor_alerts_slack_channel }}"
            text: |-
                  {{ "{{" }} range .Alerts {{ "}}" }}
                    *Alert:* {{ "{{" }} .Annotations.message {{ "}}" }} - `{{ "{{" }} .Labels.severity {{ "}}" }}`
                    *Description:* {{ "{{" }} .Annotations.message {{ "}}" }}
                    *Details:*
                    {{ "{{" }} range .Labels.SortedPairs {{ "}}" }} • *{{ "{{" }} .Name {{ "}}" }}:* `{{ "{{" }} .Value {{ "}}" }}`
                    {{ "{{" }} end {{ "}}" }}
                  {{ "{{" }} end {{ "}}" }}
            icon_emoji: ':dart:'
      - name: 'dp-slack'
        slack_configs:
          - send_resolved: true
            api_url: "{{ dp_monitor_alerts_slack_url }}"
            username: 'Monitor - Alerter'
            channel: "{{ dp_monitor_alerts_slack_channel }}"
            text: |-
                  {{ "{{" }} range .Alerts {{ "}}" }}
                    *Alert:* {{ "{{" }} .Annotations.message {{ "}}" }} - `{{ "{{" }} .Labels.severity {{ "}}" }}`
                    *Description:* {{ "{{" }} .Annotations.message {{ "}}" }}
                    *Details:*
                    {{ "{{" }} range .Labels.SortedPairs {{ "}}" }} • *{{ "{{" }} .Name {{ "}}" }}:* `{{ "{{" }} .Value {{ "}}" }}`
                    {{ "{{" }} end {{ "}}" }}
                  {{ "{{" }} end {{ "}}" }}
            icon_emoji: ':dart:' 
      {% for item in alert_teams %}
      # Comment to ensure proper indentation while templating
      - name: "{{ item.team }}"
        email_configs:
          - send_resolved: true
            to: '{{ item.alerts_mailing_list }}'
            html: '{% raw %}{{ template "email.default.html" . }}{% endraw %}'
            headers:
              subject: '[{{ kubernetes_cluster_name }}] {% raw %}{{ .GroupLabels.alertname }}{% endraw %}'
      {% if item.severity_mailing_filter is defined and item.severity_mailing_filter|length %}
      {% for filter in item.severity_mailing_filter %}
      # Comment to ensure proper indentation while templating
      - name: "{{ item.team }}_{{ filter.severity }}"
        email_configs:
          - send_resolved: true
            to: '{{ filter.alerts_mailing_list }}'
            html: '{% raw %}{{ template "email.default.html" . }}{% endraw %}'
            headers:
              subject: '[{{ kubernetes_cluster_name }}] {% raw %}{{ .GroupLabels.alertname }}{% endraw %}'
      {% endfor %}
      {% endif %}
      {% endfor %}
      # Comment to ensure proper indentation while templating
      - name: {{env}}_devops_team
        email_configs:
          - send_resolved: true
            to: '{{ default_mailing_list }}'
            html: '{% raw %}{{ template "email.default.html" . }}{% endraw %}'
            headers:
              subject: '[{{ kubernetes_cluster_name }}] {% raw %}{{ .GroupLabels.alertname }}{% endraw %}'


grafana:
  image:
    repository: grafana/grafana
    tag: 7.0.6
    pullPolicy: IfNotPresent
  env:
    GF_SERVER_ROOT_URL: http://grafana.local.com/grafana
  adminPassword: {{ (grafana_admin_password| default('prom-operator'))}}
{% if grafana_data_sources is defined and grafana_data_sources %}
  additionalDataSources: {{ (grafana_data_sources) | to_json}}
{% endif %}
{% if grafana_persistence is defined and grafana_persistence %}
  persistence: {{ grafana_persistence|to_json}}
{% endif %}
{% if grafana_service is defined and grafana_service %}
  service: {{ grafana_service|to_json}}
{% endif %}
