---
sunbird_auth_version: 1.0v
keycloak_pkg_src: https://downloads.jboss.org/keycloak/3.2.0.Final/keycloak-3.2.0.Final.tar.gz
postgresql_driver_src: https://jdbc.postgresql.org/download/postgresql-9.4.1212.jar
keycloak_pkg_file: "keycloak-3.2.0.Final.tar.gz"
keycloak_sms_provider_build: "keycloak-email-phone-autthenticator-1.0-SNAPSHOT.jar"
keycloak_subsystem: '
    <subsystem xmlns="urn:jboss:domain:keycloak-server:1.1">
        <web-context>auth</web-context>
    </subsystem>'
keycloak_cache_container: '
    <cache-container name="keycloak" jndi-name="infinispan/Keycloak">
        <local-cache name="realms"/>
        <local-cache name="users"/>
        <local-cache name="sessions"/>
        <local-cache name="offlineSessions"/>
        <local-cache name="loginFailures"/>
    </cache-container>'
keycloak_default_ds: '
    <datasource jndi-name="java:jboss/datasources/KeycloakDS"
      pool-name="KeycloakDS" enabled="true" use-java-context="true">
        <connection-url>
            jdbc:h2:${jboss.server.data.dir}/keycloak;AUTO_SERVER=TRUE
        </connection-url>
        <driver>h2</driver>
        <security>
            <user-name>sa</user-name>
            <password>sa</password>
        </security>
    </datasource>'

keycloak_ds_driver_path: "/opt/keycloak/modules/system/layers/keycloak/org/postgresql/main"
wildfly_dir: /opt/keycloak
keycloak_download_dir: /opt
keycloak_download_url: https://downloads.jboss.org/keycloak/3.2.0.Final/keycloak-3.2.0.Final.tar.gz
wildfly_user: keycloak
wildfly_group: keycloak
wildfly_standalone_config_path: /opt/keycloak/keycloak/standalone/configuration/standalone-ha.xml
keycloak_ext:  <extension module="org.keycloak.keycloak-server-subsystem"/>
keycloak_download_file: keycloak-3.2.0.Final.tar.gz

keycloak_ds_driver_url: https://jdbc.postgresql.org/download/postgresql-9.2.1212.jar
keycloak_ds_driver_name: "postgresql"
keycloak_ds_driver_module: '
    <?xml version="1.0" ?>
    <module xmlns="urn:jboss:module:1.1" name="org.postgresql">

        <resources>
            <resource-root path="postgresql-42.1.1.jar"/>
        </resources>

        <dependencies>
            <module name="javax.api"/>
            <module name="javax.transaction.api"/>
        </dependencies>
    </module>'
keycloak_custom_driver: '
    <driver name="postgresql" module="org.postgresql">
        <xa-datasource-class>
            org.postgresql.xa.PGXADataSource
        </xa-datasource-class>
        <datasource-class>org.postgresql.ds.PGPoolingDataSource</datasource-class>
    </driver>'
keycloak_custom_ds: '
    <datasource jta="true" jndi-name="java:jboss/datasources/KeycloakDS" pool-name="KeycloakDS" enabled="true" use-ccm="true">
        <connection-url>jdbc:postgresql://11.0.0.6:5432/keycloak</connection-url>
        <driver-class>org.postgresql.Driver</driver-class>
        <driver>postgresql</driver>
        <security>
            <user-name>keycloak</user-name>
            <password>KeyCloaK#2</password>
        </security>
        <validation>
            <valid-connection-checker class-name="org.jboss.jca.adapters.jdbc.extensions.postgres.PostgreSQLValidConnectionChecker"/>
            <background-validation>true</background-validation>
            <exception-sorter class-name="org.jboss.jca.adapters.jdbc.extensions.postgres.PostgreSQLExceptionSorter"/>
        </validation>
    </datasource>'

keycloak_heap_size: 512m
keycloak_metaspace_size: 256m
theme: "sunrise.tar.gz"
dest_theme: "/opt/keycloak/themes/"
theme_file: sunrise
keycloak_home: /opt/keycloak
login_theme: artifacts/sunbird/login
email_theme: artifacts/sunbird/email
tenant_name: sunbird
