{{- if (empty .Values.existingConfigMap) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fluent-bit.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "fluent-bit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  fluent-bit-service.conf: |
    [SERVICE]
        Flush        {{ .Values.service.flush }}
        Daemon       Off
        Log_Level    {{ .Values.service.logLevel }}
        Parsers_File parsers.conf
{{- if .Values.parsers.enabled }}
        Parsers_File parsers_custom.conf
{{- end }}
{{- if .Values.metrics.enabled }}
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020
{{- end }}

  fluent-bit-input.conf: |
    [INPUT]
        Name             tail
        Path             {{ .Values.input.tail.path }}
        Parser           {{ .Values.input.tail.parser }}
        Tag              {{ .Values.filter.kubeTag }}.*
        Refresh_Interval 5
        Mem_Buf_Limit    {{ .Values.input.tail.memBufLimit }}
        Skip_Long_Lines  On
{{- if .Values.input.tail.ignore_older }}
        Ignore_Older    {{ .Values.input.tail.ignore_older }}
{{- end }}
{{- if .Values.trackOffsets }}
        DB               /tail-db/tail-containers-state.db
        DB.Sync          Normal
{{- end }}
{{- if .Values.input.systemd.enabled }}
    [INPUT]
        Name            systemd
        Tag             {{ .Values.input.systemd.tag }}
{{- range $value := .Values.input.systemd.filters.systemdUnit }}
        Systemd_Filter  _SYSTEMD_UNIT={{ $value }}
{{- end }}
        Max_Entries     {{ .Values.input.systemd.maxEntries }}
        Read_From_Tail  {{ .Values.input.systemd.readFromTail }}
{{- end }}
{{ if .Values.extraEntries.input }}
{{ .Values.extraEntries.input | indent 8 }}
{{- end }}

  fluent-bit-filter.conf: |
    [FILTER]
        Name                kubernetes
        Match               {{ .Values.filter.kubeTag }}.*
        Kube_Tag_Prefix     {{ .Values.filter.kubeTagPrefix }}
        Kube_URL            {{ .Values.filter.kubeURL }}
        Kube_CA_File        {{ .Values.filter.kubeCAFile }}
        Kube_Token_File     {{ .Values.filter.kubeTokenFile }}
{{- if .Values.filter.mergeJSONLog }}
        Merge_Log           On
{{- end }}
{{- if .Values.filter.mergeLogKey }}
        Merge_Log_Key       {{ .Values.filter.mergeLogKey }}
{{- end }}
{{- if .Values.filter.enableParser }}
        K8S-Logging.Parser  On
{{- end }}
{{- if .Values.filter.enableExclude }}
        K8S-Logging.Exclude On
{{- end -}}
{{ if .Values.extraEntries.filter }}
{{ .Values.extraEntries.filter | indent 8 }}
{{- end }}

        Name                envoyparser
        Match               kube.istio-proxy.*
        Key_Name            log
        Parser              envoy
        Reserve_Data        On

  fluent-bit-output.conf: |
{{- if eq .Values.backend.type "test" }}
    [OUTPUT]
        Name  file
        Match *
        Path /tmp/fluent-bit.log
{{ else if eq .Values.backend.type "forward" }}
    [OUTPUT]
        Name          forward
        Match         *
        Host          {{ .Values.backend.forward.host }}
        Port          {{ .Values.backend.forward.port }}
        Retry_Limit False
{{- if .Values.backend.forward.shared_key }}
        Shared_Key    {{ .Values.backend.forward.shared_key }}
{{- end }}
{{- if .Values.backend.forward.tls }}
        tls           {{ .Values.backend.forward.tls }}
{{- end }}
{{- if .Values.backend.forward.tls_verify }}
        tls.verify    {{ .Values.backend.forward.tls_verify }}
{{- end }}
{{- if .Values.backend.forward.tls_debug }}
        tls.debug     {{ .Values.backend.forward.tls_debug }}
{{- end }}
{{ else if eq .Values.backend.type "es" }}
    [OUTPUT]
        Name  es
        Match *
        Host  {{ .Values.backend.es.host }}
        Port  {{ .Values.backend.es.port }}
        Logstash_Format {{ default "On" .Values.backend.es.logstash_format  }}
        Retry_Limit {{ .Values.backend.es.retry_limit }}
        Type  {{ .Values.backend.es.type }}
{{- if .Values.backend.es.time_key }}
        Time_Key {{ .Values.backend.es.time_key }}
{{- end }}
{{- if .Values.backend.es.replace_dots }}
        Replace_Dots {{ .Values.backend.es.replace_dots }}
{{- end }}
{{- if .Values.backend.es.logstash_prefix }}
        Logstash_Prefix {{ .Values.backend.es.logstash_prefix }}
{{ else if .Values.backend.es.index }}
        Index {{ .Values.backend.es.index }}
{{- end }}
{{- if .Values.backend.es.http_user }}
        HTTP_User {{ .Values.backend.es.http_user }}
{{- if .Values.backend.es.http_passwd }}
        HTTP_Passwd {{ .Values.backend.es.http_passwd }}
{{- else }}
        HTTP_Passwd ${HTTP_PASSWORD}
{{- end }}
{{- end }}
{{if eq .Values.backend.es.tls "on" }}
        tls {{ .Values.backend.es.tls }}
        tls.verify {{ .Values.backend.es.tls_verify }}
        tls.debug {{ .Values.backend.es.tls_debug }}
{{- if .Values.backend.es.tls_ca }}
        tls.ca_file /secure/es-tls-ca.crt
{{- end }}
{{- end }}
{{- end }}

  fluent-bit.conf: |
{{ .Values.rawConfig | indent 4 }}

  parsers.conf: |
{{- if .Values.parsers.regex }}
{{- range .Values.parsers.regex }}
    [PARSER]
        Name        {{ .name }}
        Format      regex
        Regex       {{ .regex }}
{{- if .timeKey }}
        Time_Key    {{ .timeKey }}
{{- end }}
{{- if .timeFormat }}
        Time_Format {{ .timeFormat }}
{{- end }}
{{ end }}
{{- end }}
    [PARSER]
        Name        dockerJson
        Format      json
        Time_Key  time
        Time_Format  %Y-%m-%dT%H:%M:%S.%L
        Time_Keep  On
        Decode_Field_As  json log
        Decode_Field_As  escaped log do_next
        Decode_Field_As  escaped_utf8 log do_next
{{- if .Values.parsers.logfmt }}
{{- range .Values.parsers.logfmt }}
    [PARSER]
        Name        {{ .name }}
        Format      logfmt
{{- if .timeKey }}
        Time_Key    {{ .timeKey }}
{{- end }}
{{- if .timeFormat }}
        Time_Format {{ .timeFormat }}
{{- end }}
{{- if .extraEntries }}
{{ .extraEntries | indent 8 }}
{{- end }}
{{ end }}
{{- end }}
{{- end }}
    [PARSER]
        Name        envoy
        Format      regex
        Regex       ^(?<host>[^ ]*) - \[(?<real_ip>[^ ]*)\] - (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*) "(?<referer>[^\"]*)" "(?<agent>[^\"]*)" (?<request_length>[^ ]*) (?<request_time>[^ ]*) \[(?<proxy_upstream_name>[^ ]*)\] (?<upstream_addr>[^ ]*) (?<upstream_response_length>[^ ]*) (?<upstream_response_time>[^ ]*) (?<upstream_status>[^ ]*) (?<last>[^$]*)
        Preserve_Key true
