# Override these values
snapshot_create_request_body: {
    type: azure,
    settings: {
      container: "elasticsearch-snapshots",
      base_path: "{{ snapshot_base_path }}"
    }
}

es_restore_host: "{{groups['es'][0]}}"
snapshot_base_path: loggerelasticsearch
