version: '3.1'

services:
  adminutil:
    image: sunbird/adminutil:{{image_tag}}
    environment:
      JAVA_OPTS: -Xms{{adminutil__initial_heap_size}} -Xmx{{adminutil__max_heap_size}}
      SERVER_PORT: {{ adminutil__port }}
      AM_ADMIN_API_ENDPOINT: {{ kong_url }}
      SPRING_PROFILES_ACTIVE: {{ adminutil__spring_profile }}
      DEFAULT_CONSUMER_GROUP: {{ adminutil__default_consumer_group }}
      ENDPOINTS_HEALTH_ID: {{ adminutil__health_id }}
      ENDPOINTS_HEALTH_SENSITIVE: "{{ adminutil__is_health_sensitive }}"
      ENDPOINTS_METRICS_ID: {{ adminutil__metrics_id }}
      ENDPOINTS_METRICS_SENSITIVE: "{{ adminutil__is_metrics_sensitive }}"
    ports:
      - {{ adminutil__port }}:4000
    networks:
      - application_default
    deploy:
      replicas: {{ adminutil_replicas }}
      resources:
        reservations:
          cpus: "{{ adminutil_reserve_cpu }}"
          memory: "{{ adminutil_reservation_memory }}"
        limits:
          cpus: "{{ adminutil_limit_cpu }}"
          memory: "{{ adminutil_limit_memory }}"
      update_config:
        parallelism: 1
        delay: 5s
    healthcheck:
      test: wget -q --spider http://localhost:4000/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  application_default:
    external: true
