---
- hosts: localhost
  become: yes
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  tasks:
    - name: upload artifact to azure storage
      include_role:
        name: azure-cloud-storage
        tasks_from: blob-upload.yml
      vars:
        blob_container_name: "{{ cloud_storage_artifacts_bucketname }}"
        container_public_access: "off"
        blob_file_name: "{{ artifact }}"
        local_file_or_folder_path: "{{ artifact_path }}"
        storage_account_name: "{{ cloud_artifact_storage_accountname }}"
        storage_account_key: "{{ cloud_artifact_storage_secret }}"
      when: cloud_service_provider == "azure"

    - name: upload artifact to gcloud storage
      include_role:
        name: gcp-cloud-storage
        tasks_from: upload.yml
      vars:
        gcp_storage_service_account_name: "{{ cloud_artifact_storage_accountname }}"
        gcp_storage_key_file: "{{ cloud_artifact_storage_secret }}"
        gcp_bucket_name: "{{ cloud_storage_artifacts_bucketname }}"
        gcp_path: "{{ artifact }}"
        local_file_or_folder_path: "{{ artifact_path }}"
      when: cloud_service_provider == "gcloud"

    - name: upload artifact to aws s3
      include_role:
        name: aws-cloud-storage
        tasks_from: upload.yml
      vars:
        local_file_or_folder_path: "{{ artifact_path }}"
        s3_bucket_name: "{{ cloud_storage_artifacts_bucketname }}"
        s3_path: "{{ artifact }}"
        aws_default_region: "{{ cloud_public_storage_region }}"
        aws_access_key_id: "{{ cloud_artifact_storage_accountname }}"
        aws_secret_access_key: "{{ cloud_artifact_storage_secret }}"
      when: cloud_service_provider == "aws"

    - name: upload artifact to oci oss
      include_role:
        name: oci-cloud-storage
        tasks_from: upload.yml
      vars:
        local_file_or_folder_path: "{{ artifact_path }}"
        oss_bucket_name: "{{ oci_artifact_oss_bucket_name }}"
        oss_path: "{{ artifact }}"
      when: cloud_service_provider == "oci"