- hosts: "{{groups['cassandra'][0]}}"
  become: yes
  environment:
    sunbird_cassandra_host: "{{ groups['cassandra'][0] }}"
    sunbird_cassandra_port: 9042
    sunbird_cassandra_groups_keyspace: sunbird_groups
    sunbird_encryption_key: "{{ core_vault_sunbird_encryption_key }}"
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  roles:
    - cassandra-deploy-groups