#  This task will take snapshot serially for all cassandra nodes
#  If we club both taking snapshot and upload the data, then the
#  interval of snapshots b/w nodes will be very high; Which might lead
#  to data discrepancies
- hosts: cassandra
  become: yes
  serial: true
  tasks:
  - name: taking cassandra snapshots
    shell: |
      nodetool clearsnapshot
      nodetool snapshot -t "cassandra-backup-{{ lookup('pipe', 'date +%Y%m%d') }}-{{ ansible_hostname }}"
  - name: sleeping 1 min b/w snapshots
    pause:
      echo: true
      minutes: 1 # A positive number of minutes to pause for.
      prompt: "Pausing after snapshot" # Optional text to use for the prompt message.

# Once snaphot is done, 
# We can take the snapshot and compress it and upload it
# This will take some cpu and memory in the nodes
# Because of that we're running it serially, so that it won't affect the perfomance
- hosts: cassandra
  serial: true
  become: yes
  vars_files:
    - ['{{ inventory_dir }}/secrets.yml']
  roles:
    - {name: cassandra-backup, vars: [ additional_arguments: "--disablesnapshot"]}
