- hosts: swarm-bootstrap-manager
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  roles:
    - stack-proxy
  tags:
    - stack-proxy
  run_once: true

- hosts: swarm-bootstrap-manager
  become: yes
  roles:
    - stack-proxy-private
  tags:
    - stack-proxy-private
  run_once: true

- hosts: swarm-bootstrap-manager
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  roles:
    - stack-api-manager
  tags:
    - stack-api-manager
  run_once: true

- hosts: swarm-bootstrap-manager
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  roles:
    - stack-sunbird
  tags:
    - stack-sunbird
  run_once: true

- hosts: swarm-bootstrap-manager
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  roles:
    - stack-adminutil
  tags:
    - stack-adminutil
  run_once: true

- hosts: swarm-bootstrap-manager
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  roles:
    - stack-keycloak
  tags:
    - stack-keycloak1
  run_once: true

- hosts: swarm-bootstrap-manager
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  roles:
    - stack-keycloak
  tags:
    - stack-keycloak2
  run_once: true

- hosts: swarm-bootstrap-manager
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  roles:
    - registry
  tags:
    - stack-registry
  run_once: true


