---
- hosts: localhost
  become: yes
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  vars:
    artifacts_container: public
    artifact: "{{playbook_dir}}/../private/utils/Desktop/{{env_name}}/faq-en.json"
    artifact_path: desktopFAQ/faq-en.json
  environment:
    AZURE_STORAGE_ACCOUNT: "{{ azure_plugin_storage_account_name }}"
    AZURE_STORAGE_KEY: "{{ azure_plugin_storage_account_key }}"
  roles:
    - artifacts-upload-azure
