- hosts: localhost
  become: yes
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  vars:
    artifacts_container: "{{desktop_container}}"
    artifact: "{{destination_path}}"
    artifact_path: "{{playbook_dir}}/../private/utils/Desktop/{{env_name}}/faq-en.json"
  environment:
    AZURE_STORAGE_ACCOUNT: "{{ sunbird_public_storage_account_name }}"
    AZURE_STORAGE_KEY: "{{ sunbird_public_storage_account_key }}"
  roles:
    - artifacts-upload-azure
  tags:
    - upload-desktop-faq
 
 
- hosts: localhost
  become: yes
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  vars:
    artifacts_container: "{{desktop_container}}"
    artifact: "{{destination_path}}"
    artifact_path: "{{playbook_dir}}/../private/utils/portal/labels/all_labels_en.json"
  environment:
    AZURE_STORAGE_ACCOUNT: "{{ sunbird_private_storage_account_name }}"
    AZURE_STORAGE_KEY: "{{ sunbird_private_storage_account_key }}"
  roles:
    - artifacts-upload-azure
  tags:
    - upload-label
