- hosts: "{{prometheus_hosts}}"
  become: yes
  vars:
    prometheus_data_dir: "{{prometheus_mount_point}}"
    prometheus_service_name: "monitor_prometheus"
  vars_files:
    - ['{{ inventory_dir }}/secrets.yml']
  environment:
    AZURE_STORAGE_ACCOUNT: "{{ backup_azure_storage_account_name }}"
    AZURE_STORAGE_KEY: "{{ backup_azure_storage_access_key }}"
  roles:
    - prometheus-restore
  tags:
    - swarm-prometheus-restore

- hosts: "{{prometheus_hosts}}"
  become: yes
  vars:
    prometheus_data_dir: "{{prometheus_fed_mount_point}}"
    prometheus_service_name: "prometheus_fed_prometheus"
  vars_files:
    - ['{{ inventory_dir }}/secrets.yml']
  environment:
    AZURE_STORAGE_ACCOUNT: "{{ backup_azure_storage_account_name }}"
    AZURE_STORAGE_KEY: "{{ backup_azure_storage_access_key }}"
  roles:
    - prometheus-restore
  tags:
    - federation-prometheus-restore

- hosts: "{{prometheus_hosts}}"
  become: yes
  vars:
    prometheus_data_dir: "{{prometheus_stateful_mount_point}}"
    prometheus_service_name: "monitor_stateful_prometheus"
  vars_files:
    - ['{{ inventory_dir }}/secrets.yml']
  environment:
    AZURE_STORAGE_ACCOUNT: "{{ backup_azure_storage_account_name }}"
    AZURE_STORAGE_KEY: "{{ backup_azure_storage_access_key }}"
  roles:
    - prometheus-restore
  tags:
    - statefull-prometheus-restore