- hosts: "cassandra"
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  roles:
   - cassandra
  tags:
   - cassandra

- hosts: es
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  roles:
    - openjdk
    - elasticsearch
  tags:
    - es

- hosts: log-es
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  roles:
    - openjdk
    - elasticsearch_old
  tags:
    - log-es

- hosts: postgresql-master
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  pre_tasks:
    - name: install setfacl support
      become: yes
      apt: pkg=acl
  roles:
    - postgresql-master
  tags:
    - postgresql-master

- hosts: postgresql-slave
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  pre_tasks:
    - name: install setfacl support
      become: yes
      apt: pkg=acl
  roles:
    - postgresql-slave
  tags:
    - postgresql-slave

- hosts: mongodb
  become: yes
  roles:
        - mongodb
  tags: 
     - mongodb

