---
apiVersion: v1
data:
  {{- range $key, $val := .Values.rccoreenv }}
  {{ $key }}: "{{ $val }}"
  {{- end }}
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.namespace }}
  
---
{{- $schemas := .Files.Glob "schemas/*" }}
{{ if $schemas }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-schema
  namespace: {{ .Values.namespace }}
data:
{{ (.Files.Glob "schemas/*").AsConfig | indent 2 }}
{{ end }}
