---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
     rollingUpdate:
        maxSurge: {{ .Values.strategy.maxsurge }}
        maxUnavailable: {{ .Values.strategy.maxunavailable }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
{{- if .Values.imagepullsecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagepullsecrets }}
{{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.dockerhub }}/{{ .Values.repository }}:{{ .Values.image_tag }}"
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}-config
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.network.port }}
        volumeMounts:
        - name: {{ .Chart.Name }}-schemas
          mountPath: /home/sunbirdrc/config/public/_schemas
        #- name: {{ .Chart.Name }}-templates
          #mountPath: /home/sunbirdrc/config/public/_schemas/templates
{{- if .Values.registry_opa_enabled }}
      - args:
        - envoy
        - --config-path
        - /config/envoy-config.yaml
        env:
        - name: ENVOY_UID
          value: "1111"
        image: envoyproxy/envoy:v1.20.0
        imagePullPolicy: IfNotPresent
        name: envoy
        {{- if .Values.envoy_healthcheck }}
        livenessProbe:
{{ toYaml .Values.envoy_livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.envoy_readinessProbe | indent 10 }}
        {{- end }}
        resources:
{{ toYaml .Values.envoy_resources | indent 10 }}
        volumeMounts:
        - mountPath: /config
          name: envoy-config
          readOnly: true
      - args:
        - run
        - --server
        - /bundle
        - --addr=localhost:8181
        - --diagnostic-addr=0.0.0.0:8282
        - --set=plugins.envoy_ext_authz_grpc.addr=:9191
        - --set=plugins.envoy_ext_authz_grpc.path=main/allow
        - --set=decision_logs.plugin=print_decision_logs_on_failure
        - --set=plugins.print_decision_logs_on_failure.stdout=true
        - --log-level=error
        - --ignore=.*
        image: sunbird/opa:0.34.2-envoy
        imagePullPolicy: IfNotPresent
        name: opa
        {{- if .Values.opa_healthcheck }}
        livenessProbe:
{{ toYaml .Values.opa_livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.opa_readinessProbe | indent 10 }}
        {{- end }}
        resources:
{{ toYaml .Values.opa_resources | indent 10 }}
        volumeMounts:
        - mountPath: /bundle
          name: opa-policy
          readOnly: true
      initContainers:
      - args:
        - -p
        - "9999"
        - -u
        - "1111"
        - -w
        - "8282,10000"
        image: openpolicyagent/proxy_init:v5
        imagePullPolicy: IfNotPresent
        name: proxy-init
        resources:
{{ toYaml .Values.initcontainer_resources | indent 10 }}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          runAsNonRoot: false
          runAsUser: 0
{{- end }}
      volumes:
      - name: {{ .Chart.Name }}-schemas
        configMap:
          name: {{ .Chart.Name }}-schemas
      #- name: {{ .Chart.Name }}-templates
        #configMap:
          #name: {{ .Chart.Name }}-templates
{{- if .Values.registry_opa_enabled }}
      - name: envoy-config
        configMap:
          name: {{ .Chart.Name }}-envoy-config
      - name: opa-policy
        configMap:
          name: {{ .Chart.Name }}-opa-policy
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
  - name: http-{{ .Chart.Name }}
    protocol: TCP
    port: {{ .Values.network.port }}
    targetPort: {{ .Values.network.targetport }}
{{- if .Values.registry_opa_enabled }}
  - name: opa-metrics
    port: 8181
    protocol: TCP
    targetPort: 8181
  - name: envoy-metrics
    port: 10000
    protocol: TCP
    targetPort: 10000
{{- end }}
  selector:
    app: {{ .Chart.Name }}
