---
- name: Remove ml-workbench if already exists else ignore error
  shell: "docker service rm ml-workbench"
  ignore_errors: yes
    
- name: Deploy ml-workbench
  shell: "docker service create --with-registry-auth -p 1111:1111 --name ml-workbench-service --hostname ml-workbench --network {{subnet_name}} {{hub_org}}/{{image_name}}:{{image_tag}}"
