---
hub_org: sunbird

proxy_replicas: 1
proxy_reservation_memory: 32M
proxy_limit_memory: 128M

proxy_prometheus: false

networks:
  - {name: 'application_default', subnet: '11.11.1.0/24'}

proxy_secrets:
  - name: prom_admin_creds
    value: "{{proxy_prometheus_admin_creds}}"
  - name: site.key
    value: "{{proxy_site_key}}"
  - name: site.crt
    value: "{{proxy_site_crt}}"
proxy_custom_config:

# These values should be overridden in inventory
proxy_site_key:
proxy_site_crt:
proxy_prometheus_admin_creds:
prometheus_route_prefix: prometheus
prometheus_alertmanager_route_prefix: alertmanager
ekstep_s3_env: "{{sunbird_env}}"
registry_url: "{{proto}}://{{proxy_server_name}}/registry"
ep_es_host:

upstream_url: "ekstep-public-{{ekstep_s3_env}}.s3-ap-south-1.amazonaws.com"
