grafana_backup_dir: /tmp/grafana-backup
grafana_data_dir: /var/dockerdata/grafana/grafana.db
# Set these vars per environment as show in example below
# Override these values in group_vars
sunbird_management_storage_account_name: 
sunbird_management_storage_account_key: '<backup_storage_key>'
grafana_backup_azure_container_name: grafana-backup

# This variable is added for the below reason -
# 1. Introduce a common variable for various clouds. In case of azure, it refers to container name, in case of aws / gcp, it refers to folder name
# 2. We want to avoid too many new variable introduction / replacement in first phase. Hence we will reuse the existing variable defined in private repo
#    or other default files and just assign the value to the newly introduced common variable 
# 3. After few releases, we will remove the older variables and use only the new variables across the repos
grafana_backup_storage: "{{ grafana_backup_azure_container_name }}"