env: dev

ml_kafka_topic_create: false
uci_kafka_topic_create: false
av_kafka_topic_create: false

processing_kafka_overriden_topics:
  - name: lms.audit.events
    retention_time: 172800000
    replication_factor: 1
  - name: lms.sso.events
    retention_time: 172800000
    replication_factor: 1
  - name: lms.user.account.merge
    retention_time: 172800000
    replication_factor: 1
  - name: lms.notification
    retention_time: 172800000
    replication_factor: 1
  

processing_kafka_topics:
  - name: lms.audit.events
    num_of_partitions: 1
    replication_factor: 1
  - name: lms.sso.events
    num_of_partitions: 4
    replication_factor: 1
  - name: lms.user.account.merge
    num_of_partitions: 1
    replication_factor: 1
  - name: lms.notification
    num_of_partitions: 1
    replication_factor: 1
 

ml_service_topics:
  - name: sl.observation.raw
    retention_time: 172800000
    replication_factor: 1
    num_of_partitions: 1
  - name: sl.observation.raw
    retention_time: 172800000
    replication_factor: 1
    num_of_partitions: 1    
  - name: sl.observation.evidence.druid
    retention_time: 172800000
    replication_factor: 1  
    num_of_partitions: 1
  - name: sl.survey.raw
    retention_time: 172800000
    replication_factor: 1
    num_of_partitions: 1
  - name: sl.survey.druid
    retention_time: 172800000
    replication_factor: 1  
    num_of_partitions: 1      
  - name: sl.survey.evidence.druid
    retention_time: 172800000
    replication_factor: 1
    num_of_partitions: 1
  - name: sl.submission.rating.raw
    retention_time: 172800000
    replication_factor: 1
    num_of_partitions: 1
  - name: sl.incomplete.observation.raw
    retention_time: 172800000
    replication_factor: 1
    num_of_partitions: 1
  - name: sl.notification.raw
    retention_time: 172800000
    replication_factor: 1
    num_of_partitions: 1
  - name: sl.incomplete.survey.raw
    retention_time: 172800000
    replication_factor: 1
    num_of_partitions: 1
  - name: sl.improvement.project.submission
    retention_time: 172800000
    replication_factor: 1
    num_of_partitions: 1

uci_service_topics:
  - name: inbound-error
    retention_time: 86400000
    replication_factor: 1
    num_of_partitions: 1
  - name: inbound-processed
    retention_time: 86400000
    replication_factor: 1
    num_of_partitions: 1
  - name: inbound-unprocessed
    retention_time: 86400000
    replication_factor: 1
    num_of_partitions: 1
  - name: outbound
    retention_time: 86400000
    replication_factor: 1
    num_of_partitions: 1
  - name: campaign
    retention_time: 86400000
    replication_factor: 1
    num_of_partitions: 1
  - name: odk.transformer
    retention_time: 86400000
    replication_factor: 1
    num_of_partitions: 1
  - name: uci.telemetry
    retention_time: 86400000
    replication_factor: 1
    num_of_partitions: 1

av_service_topics:
  - name: av.question.bulkupload
    retention_time: 172800000
    replication_factor: 1
    num_of_partitions: 1