---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
     rollingUpdate:
        maxSurge: {{ .Values.strategy.maxsurge }}
        maxUnavailable: {{ .Values.strategy.maxunavailable }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
{{- if .Values.imagepullsecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagepullsecrets }}
{{- end }}
      volumes:
        - name: {{ .Chart.Name }}-service
          configMap:
            name: {{ .Chart.Name }}-config

        - name: assessment-fcm-keystore
          configMap:
            name: assessment-fcm-keystore

        - name: improvement-fcm-keystore
          configMap:
            name: improvement-fcm-keystore

        - name: gcp
          configMap:
            name: gcp

        - name: fcm-keystore
          configMap:
            name: fcm-keystore
        
{{- $keys := .Files.Glob "keys/*" }}
{{- if $keys }}
        - name: access-keys
          secret:
            secretName: ml-core-access-keys
{{ end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.dockerhub }}/{{ .Values.repository }}:{{ .Values.image_tag }}"
        imagePullPolicy: Always
        
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}-config
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.network.port }}
        {{- if .Values.healthcheck }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        {{- end }}

        volumeMounts:
          - name: assessment-fcm-keystore
            mountPath: /opt/kendra/config/credentials/assessment-fcm-keystore.json
            subPath: assessment-fcm-keystore.json
          - name: improvement-fcm-keystore
            mountPath: /opt/kendra/config/credentials/improvement-fcm-keystore.json
            subPath: improvement-fcm-keystore.json
          - name: gcp
            mountPath: /opt/kendra/config/credentials/gcp.json
            subPath: gcp.json
          - name: fcm-keystore
            mountPath: /opt/kendra/config/credentials/fcm-keystore.json
            subPath: fcm-keystore.json

{{- $keys := .Files.Glob "keys/*" }}
{{- if $keys }}
          - mountPath: {{ .Values.ml_core_access_basepath }}
            name: access-keys
{{ end }}


          
          
          
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
  - name: http-{{ .Chart.Name }}
    protocol: TCP
    port: {{ .Values.network.targetport }}
  selector:
    app: {{ .Chart.Name }}
