- name: Status service
  become: true
  command: /etc/init.d/keycloak status
  register: keycloak
  poll: 5
  async: 10

- name: Stop service
  become: true
  command: /etc/init.d/keycloak stop && Pkill keycloak
  when: "keycloak.stdout.find('running') != -1"
  poll: 5
  async: 10
  ignore_errors: true

- name: Adding ENV Vars to bashrc
  lineinfile:
    path: '/etc/environment'
    line: '{{item.var}}={{item.value}}'
    regexp: "{{ item.var }}.*"
  with_items:
    - {var: 'sunbird_user_service_base_url', value: '{{ sunbird_user_service_base_url }}'}

- name: Remove old ENV Vars from environemt file
  lineinfile:
    path: '/etc/environment'
    line: '{{item.var}}'
    regexp: "{{ item.var }}.*"
    state: absent
  with_items:
    - {var: 'sunbird_lms_base_url'}
    - {var: 'sunbird_authorization'}
    - {var: 'sunbird_encryption_key'}
    - {var: 'sunbird_sso_username'}
    - {var: 'sunbird_sso_password'}
    - {var: 'sunbird_sso_url'}
    - {var: 'sunbird_sso_realm'}
    - {var: 'sunbird_sso_client_id'}
    - {var: 'sunbird_cassandra_host'}
    - {var: 'sunbird_cs_base_url'}

- name: Remove keycloak
  become: true
  file:
    path: "{{ keycloak_home }}"
    state: absent
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    force: true

- name: Paste keycloak package on server
  copy:
    src: "{{ artifact_path }}"
    dest: "/opt/"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    force: true

- name: Extarct the folder
  unarchive:
    src: "/opt/{{ artifact }}"
    dest: /opt/
    copy: false
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"

- name: Move the folder name
  command: mv sunbird_auth_{{ sunbird_auth_version }} keycloak
  args:
    chdir: /opt

- name: Remove the opt/{{ artifact }}
  become: true
  file:
    path: "/opt/{{ artifact }}"
    state: absent
    force: true

- name: Create required directories
  file:
    path: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
  - {dest: '{{ keycloak_home }}/providers', mode: '0755'}
  - {dest: '{{ keycloak_home }}/modules/system/layers/keycloak/org/postgresql/main', mode: '0755'}
  - {dest: '{{ keycloak_home }}/themes/{{ tenant_name }}/login/messages', mode: '0755'}
  - {dest: '{{ keycloak_home }}/themes/{{ tenant_name }}/login/resources/css/fonts/notosans', mode: '0755'}
  - {dest: '{{ keycloak_home }}/themes/{{ tenant_name }}/login/resources/css/themes/default/assets/fonts', mode: '0755'}
  - {dest: '{{ keycloak_home }}/themes/{{ tenant_name }}/login/resources/img', mode: '0755'}
  - {dest: '{{ keycloak_home }}/themes/{{ tenant_name }}/login/resources/js', mode: '0755'}
  - {dest: '{{ keycloak_home }}/themes/{{ tenant_name }}/email/html', mode: '0755'}
  - {dest: '{{ keycloak_home }}/themes/{{ tenant_name }}/email/messages', mode: '0755'}
  - {dest: '{{ keycloak_home }}/themes/{{ tenant_name }}/email/text', mode: '0755'}

- name: Copy login theme
  copy:
    src: "{{ login_theme }}/"
    dest: "{{ keycloak_home }}/themes/{{ tenant_name }}/login/"
    force: "yes"

- name: Copy Custom Validation theme html to login theme
  copy:
    src: "../../../sunbird-auth/keycloak/sms-provider/templates/"
    dest: "{{ keycloak_home }}/themes/{{ tenant_name }}/login/"
    force: true

- name: Copy email theme
  copy:
    src: "{{ email_theme }}/"
    dest: "{{ keycloak_home }}/themes/{{ tenant_name }}/email/"
    force: true

- name: Create directory for sunbird auth package config
  file:
    path: sunbird_auth_{{ sunbird_auth_version }}.config
    state: directory
    mode: 0755
    force: true

- name: Keycloak configuration XML file
  template:
    src: "roles/keycloak-deploy/templates/standalone-ha.xml"
    dest: "sunbird_auth_{{ sunbird_auth_version }}.config/standalone-ha.xml"
    mode: 0750

- name: Postgresql Configuration- module.xml
  template:
    src: "roles/keycloak-deploy/templates/module.xml.j2"
    dest: "sunbird_auth_{{ sunbird_auth_version }}.config/module.xml"
    mode: 0750

- name: SMS provider configuration file
  template:
    src: "roles/keycloak-deploy/templates/Msg91Creds.json.j2"
    dest: "sunbird_auth_{{ sunbird_auth_version }}.config/Msg91Creds.json"
    mode: 0755
  when: "{{ msg_91_required|default(false) }}"
  ignore_errors: true

- name: Keycloak configuration XML file
  copy:
    src: "sunbird_auth_{{ sunbird_auth_version }}.config/standalone-ha.xml"
    dest: "{{ keycloak_home }}/standalone/configuration/standalone-ha.xml"
    mode: 0750
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    remote_src: true

- name: Keycloak standalone.conf file
  template:
    src: templates/standalone.conf.j2
    dest: "{{ keycloak_home }}/bin/standalone.conf"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    mode: 0755

- name: Postgresql Configuration- module.xml
  copy:
    src: "sunbird_auth_{{ sunbird_auth_version }}.config/module.xml"
    dest: "{{ keycloak_home }}/modules/system/layers/keycloak/org/postgresql/main/module.xml"
    mode: 0750
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    remote_src: true

- name: Create a directory for SMS provider configuration
  file:
    path: "{{ keycloak_home }}/bin/sms-provider"
    state: directory
    mode: 0755
  when: "{{ msg_91_required|default(false) }}"
  ignore_errors: true

- name: SMS provider configuration file
  copy:
    src: "sunbird_auth_{{ sunbird_auth_version }}.config/Msg91Creds.json"
    dest: "{{ keycloak_home }}/bin/sms-provider/Msg91Creds.json"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    mode: 0755
    remote_src: true
  when: "{{ msg_91_required|default(false) }}"
  ignore_errors: true

- name: Remove the sunbird_auth_{{ sunbird_auth_version }}.config
  become: true
  file:
    path: ./sunbird_auth_{{ sunbird_auth_version }}.config
    state: absent
    force: true

- name: Overriding JAVA_HOME
  become: true
  lineinfile:
    regexp: '^SERVER_OPTS=""'
    insertafter: '^SERVER_OPTS=""'
    line: 'JAVA_HOME=""'
    path: "{{ keycloak_home }}/bin/standalone.sh"

- name: Start service
  become: true
  command: /etc/init.d/keycloak start
  poll: 5
  async: 5
