# postgresql_users should only be created in master and replicated to slave
postgresql_databases:
  - name: "{{kong_postgres_database}}"
  - name: "{{keycloak_postgres_database}}"
  - name: "{{application_postgres_database}}"

postgresql_users:
  - name: "{{ postgres_replication_user_name }}"
    password: "{{ postgres_replication_user_password }}"
    role_attr_flags: REPLICATION
  - name: "{{ postgres_exporter_user }}"
    password: "{{ postgres_exporter_password }}"
    role_attr_flags: SUPERUSER
  - name: "{{kong_postgres_user}}"
    password: "{{kong_postgres_password}}"
    db: "{{kong_postgres_database}}"
    priv: "ALL"
  - name: "{{keycloak_postgres_user}}"
    password: "{{keycloak_postgres_password}}"
    db: "{{keycloak_postgres_database}}"
    priv: "ALL"
  - name: "{{application_postgres_user}}"
    password: "{{application_postgres_password}}"
    db: "{{application_postgres_database}}"
    priv: "ALL"
