apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  KONG_ADMIN_LISTEN: "{{ .Values.kong_admin_listen }}"
  KONG_DATABASE: "{{ .Values.kong_database }}"
  KONG_LOG_LEVEL: "{{ .Values.kong_log_level }}"
  KONG_LUA_SOCKET_POOL_SIZE: "{{ .Values.kong_lua_socket_pool_size }}"
  KONG_MEM_CACHE_SIZE: "{{ .Values.kong_mem_cache_size }}"
  KONG_NGINX_WORKER_PROCESSES: "{{ .Values.kong_nginx_worker_processes }}"
  KONG_PG_DATABASE: "{{ .Values.kong_pg_database }}"
  KONG_PG_HOST: "{{ .Values.kong_pg_host }}"
  KONG_PG_PASSWORD: "{{ .Values.kong_pg_password }}"
  KONG_PG_SSL: "{{ .Values.kong_pg_ssl }}"
  KONG_PG_USER: "{{ .Values.kong_pg_user }}"
  KONG_PROXY_ACCESS_LOG: "{{ .Values.kong_proxy_access_log }}"
  KONG_RATELIMIT_CACHE_SIZE: "{{ .Values.kong_ratelimit_cache_size }}"
  KONG_TRUSTED_IPS: "{{ .Values.kong_trusted_ips }}"
  KONG_UPSTREAM_KEEPALIVE: "{{ .Values.kong_upstream_keepalive }}"
